### ISSUE TITLE
Generalized Eigenvalues

### ISSUE THREAD

**Issue by yixuan** [yixuan/spectra#1]
Moved from https://github.com/yixuan/arpack-eigen/issues/2

**Comment by skn123** [comment]
Hi Yixuan, any update on this?

**Comment by yixuan** [comment]
Ah, sorry for the slow progress on this. When I find some free time I'll catch up.

**Comment by Barry845** [comment]
Nice work.
Right now I'm using my own C++ interface to ARPACK-NG based on Arpack++ and in-house code. But your code looks quite light and easy to integrate (we are using Eigen for our project), the only thing missing is Generalized Eigenvalue support.
Any plans on doing this ?

**Comment by yixuan** [comment]
One thing I was struggling with is how to design the API of generalized solver: there are many different modes to compute the generalized eigenvalues, according to ARPACK manual. How to unify these interfaces is a problem. Maybe I should learn some design from ARPACK++, or do you have any suggestions? @skn123 @Barry845

**Comment by skn123** [comment]
I think a simple API would suffice. LHS matrix and a RHS matrix

**Comment by manusethi** [comment]
Hi @yixuan 
In one of the comments on arpack-eigen you mentioned that we can construct our own operations class to handle the generalized eigenvalue problem. Could you give some direction on how that can be done?

**Comment by yixuan** [comment]
Hi @manusethi , please see the comments below.

![geneigs](https://cloud.githubusercontent.com/assets/216398/19586145/8bb8f508-9720-11e6-8993-f688ed4deec8.png)

**Comment by manusethi** [comment]
Thanks @yixuan. However, I do not want to invert the matrix. Both my matrices are sparse and inverting one of them will make it dense.

**Comment by yixuan** [comment]
Computing generalized eigenvalue does require some form of matrix inversion, either on the A matrix or on the B matrix. For sparse matrix there is a sparse Cholesky decomposition algorithm, which in Eigen is done by the [SimplicialLLT](http://eigen.tuxfamily.org/dox/classEigen_1_1SimplicialLLT.html) solver.

Actually I have already written a [generalized eigen solver](https://github.com/yixuan/spectra/blob/master/include/SymGEigsSolver.h) using Cholesky decomposition, but the documentation is not ready yet.

**Comment by manusethi** [comment]
Thanks @yixuan, I appreciate it indeed! Could you help me with calling the eigs function for this class or provide a brief documentation? I am having some problem providing the cholesky decomposition.

**Comment by yixuan** [comment]
How do you store your sparse matrix? You may want to convert it to an Eigen sparse matrix, and then I could show you some sample code.

**Comment by manusethi** [comment]
Hi @yixuan I have already converted my matrix into a sparse matrix. I don't know how to call your function. i get some error. Here is what I did:

Eigen::SparseMatrix<double> A  ;
Eigen::SparseMatrix<double> B ;

/*
* I have not specified above how I have allocated 
* values in A and B. But Both A and B are correct 
* and I have verified their values.
* After that I did the following:
*/

Spectra::SparseGenMatProd<double> op1(A) ;
Spectra::SparseGenMatProd<double> op2(B) ;

/* 
* After that I don't know how to proceed.
* I also tried the cholesky but don't know how to specify in your new function.
*/

Eigen::SimplicialLLT< Eigen::SparseMatrix<double> > lltofB(B) ;

Spectra::SymGEigsSolver<double, Spectra::SMALLEST_MAGN,
		Spectra::SparseGenMatProd<double>, Eigen::SimplicialLLT< Eigen::SparseMatrix<double>>, Spectra::GEIGS_CHOLESKY > eigs(&op1, &lltofB, nvec, nvec+6);

/* I would greatly appreciate a sample  code */

Also, does Arpack also take the inverse of the B matrix while computing generalized eigenvalues?

**Comment by manusethi** [comment]
Hi @yixuan I have already converted my matrix into a sparse matrix. I don't know how to call your function. i get some error. Here is what I did:

Eigen::SparseMatrix<double> A  ;
Eigen::SparseMatrix<double> B ;

/*
* I have not specified above how I have allocated 
* values in A and B. But Both A and B are correct 
* and I have verified their values.
* After that I did the following:
*/

Spectra::SparseGenMatProd<double> op1(A) ;
Spectra::SparseGenMatProd<double> op2(B) ;

/* 
* After that I don't know how to proceed.
* I also tried the cholesky but don't know how to specify in your new function.
*/

Eigen::SimplicialLLT< Eigen::SparseMatrix<double> > lltofB(B) ;

Spectra::SymGEigsSolver<double, Spectra::SMALLEST_MAGN,
		Spectra::SparseGenMatProd<double>, Eigen::SimplicialLLT< Eigen::SparseMatrix<double>>, Spectra::GEIGS_CHOLESKY > eigs(&op1, &lltofB, nvec, nvec+6);

/* I would greatly appreciate a sample  code */

Also, does Arpack also take the inverse of the B matrix while computing generalized eigenvalues?

**Comment by manusethi** [comment]
Hi @yixuan I have already converted my matrix into a sparse matrix. I don't know how to call your function. i get some error. Here is what I did:

Eigen::SparseMatrix<double> A  ;
Eigen::SparseMatrix<double> B ;

/*
* I have not specified above how I have allocated 
* values in A and B. But Both A and B are correct 
* and I have verified their values.
* After that I did the following:
*/

Spectra::SparseGenMatProd<double> op1(A) ;
Spectra::SparseGenMatProd<double> op2(B) ;

/* 
* After that I don't know how to proceed.
* I also tried the cholesky but don't know how to specify in your new function.
*/

Eigen::SimplicialLLT< Eigen::SparseMatrix<double> > lltofB(B) ;

Spectra::SymGEigsSolver<double, Spectra::SMALLEST_MAGN,
		Spectra::SparseGenMatProd<double>, Eigen::SimplicialLLT< Eigen::SparseMatrix<double>>, Spectra::GEIGS_CHOLESKY > eigs(&op1, &lltofB, nvec, nvec+6);

/* I would greatly appreciate a sample  code */

Also, does Arpack also take the inverse of the B matrix while computing generalized eigenvalues?

**Comment by manusethi** [comment]
Hi @yixuan I have already converted my matrix into a sparse matrix. I don't know how to call your function. i get some error. Here is what I did:

Eigen::SparseMatrix<double> A  ;
Eigen::SparseMatrix<double> B ;

/*
* I have not specified above how I have allocated 
* values in A and B. But Both A and B are correct 
* and I have verified their values.
* After that I did the following:
*/

Spectra::SparseGenMatProd<double> op1(A) ;
Spectra::SparseGenMatProd<double> op2(B) ;

/* 
* After that I don't know how to proceed.
* I also tried the cholesky but don't know how to specify in your new function.
*/

Eigen::SimplicialLLT< Eigen::SparseMatrix<double> > lltofB(B) ;

Spectra::SymGEigsSolver<double, Spectra::SMALLEST_MAGN,
		Spectra::SparseGenMatProd<double>, Eigen::SimplicialLLT< Eigen::SparseMatrix<double>>, Spectra::GEIGS_CHOLESKY > eigs(&op1, &lltofB, nvec, nvec+6);

/* I would greatly appreciate a sample  code */

Also, does Arpack also take the inverse of the B matrix while computing generalized eigenvalues?

**Comment by manusethi** [comment]
Hi @yixuan I have already converted my matrix into a sparse matrix. I don't know how to call your function. i get some error. Here is what I did:

Eigen::SparseMatrix<double> A  ;
Eigen::SparseMatrix<double> B ;

/*
* I have not specified above how I have allocated 
* values in A and B. But Both A and B are correct 
* and I have verified their values.
* After that I did the following:
*/

Spectra::SparseGenMatProd<double> op1(A) ;
Spectra::SparseGenMatProd<double> op2(B) ;

/* 
* After that I don't know how to proceed.
* I also tried the cholesky but don't know how to specify in your new function.
*/

Eigen::SimplicialLLT< Eigen::SparseMatrix<double> > lltofB(B) ;

Spectra::SymGEigsSolver<double, Spectra::SMALLEST_MAGN,
		Spectra::SparseGenMatProd<double>, Eigen::SimplicialLLT< Eigen::SparseMatrix<double>>, Spectra::GEIGS_CHOLESKY > eigs(&op1, &lltofB, nvec, nvec+6);

/* I would greatly appreciate a sample  code */

Also, does Arpack also take the inverse of the B matrix while computing generalized eigenvalues?

**Comment by manusethi** [comment]
Hi @yixuan I have already converted my matrix into a sparse matrix. I don't know how to call your function. i get some error. Here is what I did:

Eigen::SparseMatrix<double> A  ;
Eigen::SparseMatrix<double> B ;

/*
* I have not specified above how I have allocated 
* values in A and B. But Both A and B are correct 
* and I have verified their values.
* After that I did the following:
*/

Spectra::SparseGenMatProd<double> op1(A) ;
Spectra::SparseGenMatProd<double> op2(B) ;

/* 
* After that I don't know how to proceed.
* I also tried the cholesky but don't know how to specify in your new function.
*/

Eigen::SimplicialLLT< Eigen::SparseMatrix<double> > lltofB(B) ;

Spectra::SymGEigsSolver<double, Spectra::SMALLEST_MAGN,
		Spectra::SparseGenMatProd<double>, Eigen::SimplicialLLT< Eigen::SparseMatrix<double>>, Spectra::GEIGS_CHOLESKY > eigs(&op1, &lltofB, nvec, nvec+6);

/* I would greatly appreciate a sample  code */

Also, does Arpack also take the inverse of the B matrix while computing generalized eigenvalues?

**Comment by yixuan** [comment]
Hi all, just to let you know that finally I've added a generalized eigen solver to Spectra. The documentation and example code can be found [here](http://yixuan.cos.name/spectra/doc/classSpectra_1_1SymGEigsSolver.html).

This implemented solver is the most basic one, and other more complicated algorithms are under development, but I think it can already solve a large number of symmetric generalized eigenvalue problems.

@manusethi, ARPACK also requires you to implement the operation `inv(B) * v`, and you need to program that by yourself. Now in Spectra this can be done via the wrapper class `SparseCholesky`. See the code in the documentation.

**Comment by manusethi** [comment]
Hi @yixuan. Thank you  very much.

BTW regarding the inverse, I have been using ARPACK++. As per their documentation I didn't need to program the inverse of B matrix. But probably they are taking the inverse like what you have described.

**Comment by manusethi** [comment]
Hi @yixuan 

I just tried your code and it worked great! Now I no longer have to deal with Arpack++ and other dependencies like SuperLU, Umfpack, BLAS etc which were creating a lot of problems for me when using with my MPI based code. Thank you so much!

**Comment by yixuan** [comment]
Glad to hear that!

**Comment by TerranRush** [comment]
Hey @yixuan 
Any plan to support the case when B is indefinite?

**Comment by yixuan** [comment]
@TerranRush 
If I get it right, you are talking about the case where `B` is indefinite but is invertible, correct?

**Comment by TerranRush** [comment]
Yes, just as the ARPACK buckling mode.

**Comment by yixuan** [comment]
@TerranRush 
I plan to implement the "regular inverse mode" first, i.e., solving `inv(B) * A * x = lambda * x`. Does this suffice to your problem?

**Comment by TerranRush** [comment]
@yixuan 
Actually, I don't know the algorithm details. According to ARPACK document, I'm looking for this one:
c  Mode 4:  K*x = lambda*KG*x, K symmetric positive semi-definite, 
c           KG symmetric indefinite
c           ===> OP = (inv[K - sigma*KG])*K  and  B = K.
c           ===> Buckling mode
I tried the unsupported ARPACK module in Eigen, but it looks this case is not well handled.
So I found your library here :)

**Comment by yixuan** [comment]
It depends on whether you want to calculate the largest (or smallest) generalized eigenvalues, or the ones that are closest (or farthest) to some given number `sigma`. The first case will use regular inverse mode, and the latter corresponds to the buckling mode.

**Comment by oberbichler** [comment]
Hi!
Is it possible to combine `SymGEigsShiftSolver` with a `ShiftSolve` operator? I try to calculate the smallest generalized eigenvalues with large symetric sparse matrices (~60000x60000).

**Comment by oberbichler** [comment]
Finally we used another algorithm. [Here you will find our implementation.](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/EigenSolversApplication/custom_solvers/eigensystem_solver.h)

**Comment by yixuan** [comment]
@oberbichler Thanks for the pointer. I'm also trying to learn new algorithms that better fit such problems.

**Comment by lobpcg** [comment]
> 
> 
> Finally we used another algorithm. [Here you will find our implementation.](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/EigenSolversApplication/custom_solvers/eigensystem_solver.h)

Anna Araslanova (LOBPCG algorithm) is already available in contributed and should likely be faster. You might want to give it a try.

**Comment by oberbichler** [comment]
Thanks for the hint! A lot of compiling errors... still WIP?

**Comment by yixuan** [comment]
Yeah, sorry about that...
I just experimentally merged the PR and didn't have time to write a test. Probably I can finish that in one or two weeks. The release of v0.7 of Spectra will be a signal.

**Comment by yixuan** [comment]
For people who are still interested, `SymGEigsShiftSolver` has been implemented in the  [1.y.z](https://github.com/yixuan/spectra/tree/1.y.z) branch. Example code is available in the [testing program](https://github.com/yixuan/spectra/blob/1.y.z/test/SymGEigsShift.cpp).

Note that this new branch contains several API-breaking changes that will be included in the next major release, so some (minor) code migration is needed.

**Comment by yixuan** [comment]
I think it is ready to close this issue now, as Spectra v1.0.0 has been released and generalized eigenvalues are fully supported.

It is also funny to see how long I took to close the very first issue of Spectra. 😆
