### ISSUE TITLE
Shift-invert on sparse matrices

### ISSUE THREAD

**Issue by Mahdisadjadi** [yixuan/spectra#10]
Can `SymEigsShiftSolver` find the eigenvalues of a `SparseGenMatProd` operation? When I use:

```
SparseGenMatProd<double> op(mat);
SymEigsShiftSolver< double, LARGEST_MAGN, 
SparseGenMatProd<double> > eigs(&op, 3, 6, 0.0);
```
I receive this error:

```
spectra/include/SymEigsSolver.h:855:21: error: no member named 'set_shift' in
      'Spectra::SparseGenMatProd<double>'
       this->m_op->set_shift(sigma);
```

**Comment by yixuan** [comment]
Hi @Mahdisadjadi, you should use the `SparseSymShiftSolve` class instead.

**Comment by Mahdisadjadi** [comment]
@yixuan : Thanks! I see, I downloaded `tar.gz` from the site and it doesn't have `SparseSymMatProd.h` header (& a few others)!

**Comment by yixuan** [comment]
Ah, notice that  `SparseSymShiftSolve` is the matrix operator, and `SymEigsShiftSolver` is the solver.
So your declaration of `eigs` should be

```cpp
SymEigsShiftSolver< double, LARGEST_MAGN, SparseSymMatProd<double> >
```

:smile:

**Comment by Mahdisadjadi** [comment]
@yixuan: Excellent, thanks! This works:

```
SparseSymShiftSolve<double> op(mat);
 SymEigsShiftSolver< double, LARGEST_MAGN, SparseSymShiftSolve<double> > eigs(&op, 3, 6, 2.0);
```
