### ISSUE TITLE
Computing the last eigenvalue/eigenvector

### ISSUE THREAD

**Issue by XL64** [yixuan/spectra#102]
Hello,

I am using Spectra::SymEigsSolver to compute the last eigen value  of plenty small problems.
Usually I don't need all the eigen values but som times it happens I have 2x2 problems in which both eigen values are relevant.
Why is the algorithm in spectra unable to compute the whole eigen values ? What would you suggest ?
Regards,

XL.

**Comment by yixuan** [comment]
The underlying algorithm is designed to compute a few eigenvalues for large matrices, but not the whole spectrum. In fact it should be faster to compute all the eigenvalues using `Eigen::SelfAdjointEigenSolver` if your matrices are small.
