### ISSUE TITLE
min max

### ISSUE THREAD

**Issue by Deviaphan** [yixuan/spectra#105]
There are problems with old-style min-max C macros, need to supplement all definitions and calls with parentheses to compile. Eigen did this.

`// Full specialization
template <>
struct TypeTraits<float>
{
    static inline float **(**min**)**()
    {
        return **(**std::numeric_limits<float>::min**)**();
    }
};`

**Comment by yixuan** [comment]
Thanks! Do I also need to to the same trick when I use `std::min` and `std::max`?

**Comment by Deviaphan** [comment]
> Do I also need to to the same trick when I use `std::min` and `std::max`?

Yes, better to enclose functions in parentheses that match standard macros. For "(std::min)(a,b)" it is also better to do this. And for templated and for simple functions.

**Comment by yixuan** [comment]
Thanks. I have done this in https://github.com/yixuan/spectra/commit/c81bcfe889422bff208dc2a1b86f68c41bc89098. Could you give a quick test? Note that I worked in the [1.y.z](https://github.com/yixuan/spectra/tree/1.y.z) branch, which will be the next major release. It breaks a lot of APIs, so you may need to change your code accordingly. Also see the [discussion](https://github.com/yixuan/spectra/issues/92) here.
