### ISSUE TITLE
The sign of part columns of eigenvectors are incorrect

### ISSUE THREAD

**Issue by soliloquy1983** [yixuan/spectra#107]
Hi, I want to calculate the largest k eigenvalues and corresponding eigenvectors, and my matrix is large, dense and non-symmetric.
The result is that the sign of some columns of eigenvectors are reversed corresponding to Matlab.
I know that if the sign of the eigenvectors is  **totally** reversed,  the  A * x = lambda * B * x, then A * (-x) = lambda * B * (-x), and the result is still right. However, my problem is **part of**  columns of eigenvectors are reversed, and the result is incorrect.
My codes are as follows:

void GetSpectraEiegen(MatrixXd &matrix, VectorXd &eigenvalue, MatrixXd eigenvector, int k)
{
 DenseGenMatProd<double> op(matrix);
 GenEigsSolver<double, LARGEST_MAGN, DEnseGenMatProd<double>>eigs(&op, k, k*2);
 eigs.init();
 eigs.compute();
 VectorXcd evalues = eigs.eigenvalues();
 VectorXd evalueR = evalues.real();
 MatrixXcd evectors = eigs.eigenvectors();
 MatrixXd evectorsR = evectors.real();
}

Are there any problems with the code, and how can i correct it ,thanks~

**Comment by yixuan** [comment]
`A * x = lambda * B * x => A * (-x) = lambda * B * (-x)` is true for each eigenvector, meaning that you can flip the sign of any eigenvector.
