### ISSUE TITLE
How to cite spectra in academic publications?

### ISSUE THREAD

**Issue by qzxuhui** [yixuan/spectra#108]
Sir, Thanks for your great job.
I want to cite spectra in my thesis. Could you please tell me how to cite spectra?
Like Eigen, its share a bibtex of how to cite Eigen: http://eigen.tuxfamily.org/index.php?title=BibTeX

**Comment by yixuan** [comment]
Thanks for using Spectra. Right now I don't have a publication associated with Spectra, so you can simply add a footnote giving the website (https://spectralib.org), or cite Spectra similar to Eigen:

```
@misc{spectralib,
    author = {Yixuan Qiu},
    title = {Spectra: C++ Library For Large Scale Eigenvalue Problems},
    howpublished = {https://spectralib.org},
    year = {2015}
}
```
