### ISSUE TITLE
smallest eigenvalues via GenEigsRealShiftSolver

### ISSUE THREAD

**Issue by ysonline** [yixuan/spectra#109]
I read: "it is advised to use the shift-and-invert mode of eigen solvers <to find the smallest eigenvalues>" and used:

GenEigsRealShiftSolver< double, SMALLEST_REAL, SparseGenRealShiftSolve< double > > eigs(&op, nev, ncv, 0.0); //please note that sigma = 0.0 

Btw, GenEigsRealShiftSolver on a 10Kx10K sparse Laplacian takes a lot of time - terminated after 20 minutes.

Any comments?

**Comment by yixuan** [comment]
Two questions here:
1. Typically the Laplacian matrix is symmetric, right? In this case why not use `SymEigsShiftSolver`?
2. In shift-and-invert mode, the selection rule is applied to `1/(λ - σ)` rather than `λ`, so what you need should be something like `LARGEST_MAGNITUDE`.

**Comment by ysonline** [comment]
Thanks for the tip; it finds 15 smallest eigenvalues/vectors in just 0.1 secs via SymEigsShiftSolver :)

**Comment by yixuan** [comment]
Cool. Can I close this issue now?

**Comment by ysonline** [comment]
Yes. Everything is fine. Thanks again for providing this cool library.
