### ISSUE TITLE
partial singular value decomposition 

### ISSUE THREAD

**Issue by jdbancal** [yixuan/spectra#11]
Hello, I just found your library and it looks like a very nice complement to Eigen for sparse matrix eigenvalue computation! Thanks a lot for sharing :+1: 

I'm wondering whether you also have some code around to compute just a few singular values. The sibling project RSpectra seems to have somethin along these lines (see file svds.cpp in https://github.com/yixuan/RSpectra/blob/master/src ). Do you think it could be possible to port this code to Spectra? Or is there a better option in your opinion?

**Comment by yixuan** [comment]
Hi @jdbancal, since SVD requires more forms of matrix operations (`A * x` and `A.transpose() * x`), I'd like to add partial SVD as an example program rather than including it in the library headers. I'll let you know once I finish.

Also, according to [the post by Bryan](https://bwlewis.github.io/irlba/comparison.html), Spectra may not be the most efficient way to calculate partial SVD. I think the algorithm introduced there also deserves a try.

**Comment by jdbancal** [comment]
Thanks for your answer @yixuan, I didn't know about irlba. It would be great to have an example of svd computation also :)

Since I'm using Eigen, and irlba doesn't seem to suport this format, I'm not sure I can benefit from it. Especially since I need to perform these computations with ad-hoc types (i.e. neither single nor double)...

By the way, concerning the eigenvalue algorithm, I see that Spectra currently only supports floats, doubles and long doubles: do you know what it would take to allow the code to support any type coming with its own algebra?

For instance, I can see that some calls to std::abs should be replaced by abs when applying to the Scalar type (otherwise the specialized abs function isn't found by the compiler), but I'm not sure if there is a lot more to do than small adaptations like that... May I ask what is your opinion?

**Comment by yixuan** [comment]
I see. When I wrote Spectra I didn't take into account other float types, but I guess with some careful substitutions of the basic math functions Spectra should apply to other types. Have you implemented the necessary traits and math functions according to [Eigen's guide](http://eigen.tuxfamily.org/dox/TopicCustomizingEigen.html)?

**Comment by jdbancal** [comment]
Thanks for your feedback! Yes, the necessary traits and math functions are there. That sounds promising, I'll give it a try :-)

**Comment by yixuan** [comment]
The partial SVD solver has been added in https://github.com/yixuan/spectra/blob/master/include/Spectra/contrib/PartialSVDSolver.h.
