### ISSUE TITLE
ARPACK interface to spectra

### ISSUE THREAD

**Issue by kapil-iitk** [yixuan/spectra#114]
I wish to use implicitly restarted Arnoldi for the generalized eigenvalue problem ( For example ARPACK routine SNAUPD, DNAUPD etc can be implemented for the generalized eigen pair problem which can include implicitly restarted Arnoldi, Lanczos algorithms; which are useful for large matrix. ). As this is not implemented in the spectra, can you share your views on how to interface ARPACK to spectra for the same? Thank you.

**Comment by yixuan** [comment]
Maybe I didn't fully get your point, but Spectra indeed contains a generalized eigen solver. Can you elaborate your question?

**Comment by yixuan** [comment]
Let me first close this issue as I didn't get any response. Feel free to reopen it if you have further explanations.
