### ISSUE TITLE
SymGEigsSolver: Strange results since the update from  "update badge link" (30. may 20) to  "merge pull request" (12. jan 21)

### ISSUE THREAD

**Issue by Spammed** [yixuan/spectra#115]
Thanks to your migration guide the update was easy for me.

I am (still) using SymGEigsSolver. But after the update, I get too many eigenmodes/-frequencies returned for one of my test cases.
The test case has only a few degrees of freedom _(ndof = 6)_ but by default I cause a certain number of eigenmodes _(e.g. nef = 10)_ to be calculated.
Previously this was not a problem and I received few _(Due to the nature of my matrices 3)_ but fully reasonable eigenmodes. 
After the update, I now receive in total min(nef, ndof-1) _(5)_ eigenmodes/-frequencies. Some _(1)_ are now missing and some _(3)_ of them are not reasonable.

In all my other test cases ndof is (usually much) larger than nef and among them, there is only one case with a very very small numerical deviation of no significance. All others are exactly the same up to the very last digit.

I will try to put together a test code for you.
But at the moment I can't estimate if and until when I will succeed.

> Motivation:
> My test system is mechanically a simple cantilever made from a simple bar element with a point mass at the end.
> I then feed SymGEigsSolver the following problem:
> ([M] + (1/w^2) [C+sM]) x = 0 -> f = sqrt(w^2 - s)/2pi
> det([M]) >= 0
> det([C+sM]) > 0

> 
> This mechanical system has, if you want to see it that way, 3 infinitely large natural frequencies, which did not disturb so far.
> Previous, meaningful natural frequencies [Hz]
> 1: .13891786E+01
> 2: .13891786E+01
> 3: .54689064E+02
> 
> Now, additional, non-sense eigenfrequencies [Hz]
> 1: .00000000E+00
> 2: .13891786E+01
> 3: .20267187E+02
> 4: .25771982E+02
> 5: .54689064E+02
>

**Comment by yixuan** [comment]
Thanks for the report. An example that reproduces the issue would be much appreciated.

**Comment by Spammed** [comment]
I now have a test in the 'new' form (see below).
The specific numbers are slightly different, but the problem remains the same: Too many and partly unreasonable eigenvalues.
I see that this time (I think wrong) negative eigenvalues occur.

#include "Eigen\Eigen"
#include <Spectra\SymGEigsSolver.h>
#include <Spectra\MatOp\SparseCholesky.h>
#include <iostream>

int main()
{
	using namespace std;
	using namespace Eigen;

	using Scalar = double;
	using Vec = Eigen::Matrix<Scalar, Dynamic, 1>;
	using Mat = SparseMatrix<Scalar>;
	using Tri = vector<Triplet<Scalar>>;

	constexpr double pi = 3.14159265358979323846;

	// Original (mechanical) Problem: 
	// (Lowest) Eigenvalues of: ([C] - w² [M])x = 0
	Tri C_tri = {
		{0,0,	1.1807575e+08},
		{1,1,	 304744.5},
		{1,5,	-152372.25},
		{2,2,	 304744.5},
		{2,4,	 152372.25},
		{3,3,	  15403.85},
		{4,2,	 152372.25},
		{4,4,	 101581.5},
		{5,1,	-152372.25},
		{5,5,	 101581.5},
	};

	Tri M_tri = {
		{0,0,	1000.0},
		{1,1,	1000.0},
		{2,2,	1000.0},
	};


	Mat C(6,6);
	C.setFromTriplets(C_tri.begin(), C_tri.end());

	Mat M(6, 6);
	M.setFromTriplets(M_tri.begin(), M_tri.end());

	std::cout << "C:\n" << C << "\n\n";
	std::cout << "M:\n" << M << "\n\n";


	// Transformed Problem:
	// (Highest) Eigenvalues of: ([A] + lam [B])x = 0
	//		A := M,				(pos. semi definit)
	//		B := [C + shift*M]	(pos. definit)
	//		-> f = sqrt(1/lam - s)/2pi
	const Scalar shift{ 1.e5 };
	Mat A = M;
	Mat B = C + shift * M;

	std::cout << "A:\n" << A << "\n\n";
	std::cout << "B:\n" << B << "\n\n";

	const auto ndof = M.cols();
	const auto nef = std::min(10, ndof - 1);
	const auto ncv = std::min(std::max(2 * nef, 50), ndof);

	using namespace Spectra;
	using OpType = SparseSymMatProd<Scalar>;
	using BOpType = SparseCholesky<Scalar>; 
	const auto geigsmode{ GEigsMode::Cholesky };

	OpType op(A);
	BOpType Bop(B);
	if (Bop.info() == CompInfo::Successful) {
		SymGEigsSolver<OpType, BOpType, geigsmode> eigs(op, Bop, nef, ncv);
		eigs.init();
		const auto nconv = eigs.compute(SortRule::LargestMagn);
		//const auto nconv = eigs.compute(SortRule::LargestReal); // <- unsupported selection rule
		if (eigs.info() == CompInfo::Successful) {
			Vec lam = 1 / (eigs.eigenvalues().array()) - shift;
			cout << "lam:\n" << lam << "\n\n";

			auto f = lam.array().sqrt() / 2 / pi;
			cout << "f [Hz]:\n" << f << "\n\n";
		} else cerr << "ERROR\n";
	} else cerr << "ERROR\n";
}

**Comment by Spammed** [comment]
I now have a test in the 'new' form.
The specific numbers are slightly different, but the problem remains the same: Too many and partly unreasonable eigenvalues.
I see that this time (I think wrong) negative eigenvalues occur.

**Comment by yixuan** [comment]
Thanks, I'll take a look.

**Comment by yixuan** [comment]
I think I have fixed this issue by https://github.com/yixuan/spectra/commit/c77513b6df28da1702aa3aa90a7ef1e4596fb2c4. Can you give it a try?

**Comment by Spammed** [comment]
Thank you very much. It seems to be the right place to look into. My original issue is fixed but an other test case now fails.
It took me some time to extract a suitable test case from my original test case, which also calculates incorrectly. Obviously it depends very much on the numerical details. But here it is:

**Comment by yixuan** [comment]
Good catch. Indeed multiple eigenvalues are always a headache for iterative eigen solvers, and even worse, the given `A` matrix is not full rank, so the solver needs to search eigenvectors that are not in the range of A. I looked at the result and there are two incorrect eigenvalues immediately after the three positive ones, so it must be related to the rank deficiency of `A`. I'll try some more robust way to detect this.

**Comment by yixuan** [comment]
Another attempt: https://github.com/yixuan/spectra/commit/975aa2f61187cfc3c243f9eeea11ee1957d7e9eb. I cannot guarantee this is universally better than before, but it seems to correct all the issues so far.

**Comment by Spammed** [comment]
Thank you very much for your work.
This version passes all my tests. I.e. it delivers the same *) plausible results as in May 2020.
Furthermore, I can observe that it is now much more robust against a carelessly selected shift parameter.
That's great!
> *) What should not bother anyone: In a few cases the sign or the eigenmodes or the order of eigenmodes of the same natural frequency changes.

I still have two educational questions:
Your SymGEigsShiftSolver works (in any mode) differently than the handmade equation shift in my test source code, right?
Do you have a hint what kind of solvers could still be considered for my kind of problem or even should be better suited, i.e. that I should give a try?

**Comment by yixuan** [comment]
Those two entries are only available in the upcoming new version, and I'll update the website when 1.0.0 is released. A preview of the new documentation can be found below.

[spectra-doc.zip](https://github.com/yixuan/spectra/files/5833091/spectra-doc.zip)

**Comment by yixuan** [comment]
For the two questions: yes, in `SymGEigsShiftSolver` there is a buckling mode that solves `C * x = lambda * M * x`, where `M` is positive semi-definite and `C` is positive definite. By specifying a shift `sigma > 0` and choosing the `SortRule::LargestAlge` selection rule, one can compute eigenvalues that are closest to but greater than `sigma`.

**Comment by Spammed** [comment]
Thank you very much for your elaborated answer. 
It looks to me like the 'buckling' method is numerically more fragile than how I currently do it.
Also, the eigenvectors look different than I think they should. Is there a 'residual error' expression similar to (E'BE-I).norm()?

Regardless of all this, I think the original problem here is solved and can be closed.

Where would be a better place to discuss general questions about suitable methods? 
Perhaps here: https://discord.com/invite/2SkEJGqZjR

**Comment by yixuan** [comment]
Right, if you look for eigenvalues close to zero then the original method seems better. In fact the buckling mode does not allow `sigma = 0`. It is more useful if you are seeking eigenvalues close to some `sigma > 0`.

**Comment by Spammed** [comment]
Thank you for the clarification. Issue solved.
