### ISSUE TITLE
spectra stability across machines

### ISSUE THREAD

**Issue by ysonline** [yixuan/spectra#120]
This is probably more of a Computer Architecture issue but I still wonder whether there's a solution:

I've moved from i7-3770 3.40GHz to i7-8700 3.20GHz and got the following small differences in my eigenvalues of the cotangent Laplacian matrix (listing a few):
4.75608e-009 --> 4.7404e-09, 4.25913e-009 --> 4.25417e-09, 3.52349e-009 --> 3.52818e-09

Similarly, a few components of an eigenvector:
0.0167258 --> -0.0167373, 0.0172545 --> -0.0172306, -0.00836465 --> 0.00835387 //I understand the arbitrary sign flip but not the content change.

Note that the content of the Laplacian matrix, which is doing cotangents and divisions, stays exactly the same, e.g., L[0][0] = 4.95677e-006 and L[401][0] = -7.23188e-007 in both machines. Is there a way so I can get the same consistency in Spectra? Why is this inconsistency happening in Spectra but not in my cotangent Laplacian content?

**Comment by JensWehner** [comment]
What is the tolerance to which you let the calculation converge? Are you using `float` or `double`

**Comment by ysonline** [comment]
Using double everywhere.
What do you mean by tolerance? I'm using GenEigsRealShiftSolver< double, LARGEST_MAGN, SparseGenRealShiftSolve< double > > eigs(&op, nev, ncv, 0.0); //the last parameter 0.0 here is the shift amount (looking for the smallest eigenvalues). I'm using 0.0 on both machines. Does it have something to do with tolerance?

**Comment by JensWehner** [comment]
in the `compute` method you can specify the tolerance of the solution you want, if you did not set it explicitly it defaults to `1e-10`. https://spectralib.org/doc/classspectra_1_1geneigsbase

So probably it is an architecture problem, which compile time options did you use? It could also be that the algorithm is unstable against small perturbations, but @yixuan knows better.

**Comment by yixuan** [comment]
One possible reason is the compiler flag. Newer CPUs usually have vectorized instructions such as AVX2, and that affects the order of low-level operations. You can try to pass `-march=x86-64` to the compiler and see the results again.

**Comment by yixuan** [comment]
Let me close this first unless you have further questions.
