### ISSUE TITLE
Release and documentation on website

### ISSUE THREAD

**Issue by cassiersg** [yixuan/spectra#121]
The "Downloads" page of the website offers the version 0.8.1, while AFAIU version 0.9 is the latest release. I'm signaling this as I'm thinking that you maybe forgot to update it ?

On a slightly different topic, it's hard to tell for which version the docs at https://spectralib.org/doc are built. Could you add a mention of the Spectra version in the docs ? (or provide a way to choose for which version to display the documentation ?)

**Comment by yixuan** [comment]
Thanks for the suggestion. I'll improve the website when I get some time.

Typically the https://spectralib.org/doc website points to the most recent version, and I forgot to update the download page. The best way to find the most recent version is to look at the Github [release page](https://github.com/yixuan/spectra/releases).

**Comment by yixuan** [comment]
The new version v1.0.0 has been released, and the website has been updated as well.
