### ISSUE TITLE
DenseGenMatProd<double> generating an empty object

### ISSUE THREAD

**Issue by Youssef-Zarca** [yixuan/spectra#123]
please i am trying to do Multiscale principal component anlysis (MSPCA) process on c++ visual studio. Its a wavelet decomposition analysis followed with a pricipal component analysis (PCA) for each WDA component.

The WDA works fine but after i have appended the decomposit with zeros and put them in one Matrix (Eigen::MatrixXd) the DenseGenMatProd<double> is creating an empty object 

m_mat -> m_Object -> m_storage = {m_data=0x00000000 {???} m_rows=0 m_cols=0 }

`Spectra::DenseGenMatProd<double> op_dense(X); 
    Spectra::GenEigsSolver< double, Spectra::LARGEST_MAGN, Spectra::DenseGenMatProd<double>> solver(&op_dense, nev, ncv); 
    solver.init();
    int nconv = solver.compute(); 
    `
Please can someone help me? The program crashes always at those lines

**Comment by yixuan** [comment]
Hi @Youssef-Zarca, can you show me more details about your code? For example how you create the matrix `X`.

**Comment by yixuan** [comment]
Let me close this first unless there are further updates.
