### ISSUE TITLE
Eigenvalues in the middle

### ISSUE THREAD

**Issue by r-barnes** [yixuan/spectra#134]
Is there a way to get _k_ eigenvalues from the middle of the spectrum, assuming it's in algebraic order?

**Comment by shivupa** [comment]
If you know the range of eigenvalues you wanted to search, the shift-invert solvers might be of interest  https://spectralib.org/doc/classspectra_1_1symeigsshiftsolver

**Comment by yixuan** [comment]
Right. At least for the current algorithm, you need to have a "target" to get the eigenvalues around that.
