### ISSUE TITLE
m_ritz_val[nev_new] with nev_new=m_ncv

### ISSUE THREAD

**Issue by jdbancal** [yixuan/spectra#14]
Hey @yixuan,

Me again ;-) I have some trouble with GenEigsSolver : the method `nev_adjusted` sometimes tries to access `m_ritz_val[nev_new]` with a value of `nev_new` which is larger than the size of the array, thus resulting in a fatal error.

From what I can see, the `m_ritz_val` vector contains `m_ncv` elements. At the same time, in the beginning of function `nev_adjusted` it looks like `nev_new` can take values up to `m_ncv` (first value `m_nev`, and then potentially increase up to `m_ncv` in the loop). When this happens, `m_ritz_val[nev_new]` leads to a segmentation fault...

The occurence of this behavior seems to be linked with the decrease of the value of `nconv` between two iterations. At least both things happen jointly. Is the algorithm safe if `nconv` decreases for some iterations (I guess only momentarily...)? Is it normal to allow for `nev_new` to take values up to `m_ncv`?

Cheers!

**Comment by yixuan** [comment]
If you encountered such situations then this should be a bug. Let me take a look.

**Comment by yixuan** [comment]
Hi @jdbancal, I think this bug has been fixed. Would you like to have a try of the most recent version?

**Comment by jdbancal** [comment]
Hey @yixuan, I tested the code which was giving a problem on the previous version of the library, and it works fine now :-) It looks like you fixed the problem. Thanks!

**Comment by yixuan** [comment]
Great! I think we can close this issue now.
