### ISSUE TITLE
More iterations are needed for some test in test/GenEigsRealShift.cpp

### ISSUE THREAD

**Issue by pgrt** [yixuan/spectra#142]
Hello,

I am working on packaging spectra 1.0.1 for Debian GNU/Linux.

On my computer, when I run test/GenEigsRealShift.cpp through CMake, I get:

-------------------------------------------------------------------------------
 Eigensolver of general real matrix [10x10]
   Smallest Real Part
 -------------------------------------------------------------------------------
 ./test/GenEigsRealShift.cpp:101
 ...............................................................................
 
 ./test/GenEigsRealShift.cpp:61: FAILED:
   REQUIRE( eigs.info() == CompInfo::Successful )
 with expansion:
   2 == 0
 with messages:
   nconv = 1
   niter = 201
   nops  = 754
 
I rose the number of iterations from 200 to 500 on line 44 of test/GenEigsRealShift.cpp, and then the test passed. I did not try with other values between 200 and 500.
I am using Debian testing (Bookworm) on amd64.

Best wishes,

Pierre

**Comment by yixuan** [comment]
Thanks. I'll increase the iteration number in the next release.

**Comment by yixuan** [comment]
This has been solved in https://github.com/yixuan/spectra/commit/1f53e26d2242cbd848cd5741f2019a91d893a9aa.
