### ISSUE TITLE
Minimum error tolerance - GenEigsSolver

### ISSUE THREAD

**Issue by yaeji43** [yixuan/spectra#143]
Hi,

Using GenEigsSolver, I calculated the eigenvalues of a large sparse matrix [6840 x 6840]. Theoretically, the real part of all eigenvalues of this matrix should be zero, but I got values mostly around 1.e-12. I think this might be related to an error tolerance set in GenEigsSolver, but I could not find any information regarding the tolerance.

Q1. What is the minimum (or initial setting) error tolerance when using GenEigsSolver?
Q2. Is there any way I can control the error tolerance?

Sincerely,

**Comment by yixuan** [comment]
In general, most computations involving floating-point numbers are subject to rounding errors, so you may not expect the real parts to be exactly zero. I would say this level of error is unavoidable, and for practical use you may simply post-process the values and manually set all real parts to be zero.
