### ISSUE TITLE
In your example sparse ev init() did dense ev init()

### ISSUE THREAD

**Issue by dziehe** [yixuan/spectra#148]
Hello,

Many thanks for your work. I tested spectra with your own example 

    int const dimN = 10000; 
    Eigen::SparseMatrix<double> M(dimN, dimN);
    M.reserve(3*dimN - 2);
    for(int iIdx = 0; iIdx < dimN; iIdx++)
    {
        M.insert(iIdx, iIdx) = -2.0;
        if(iIdx > 0)
           M.insert(iIdx - 1, iIdx) = 1.0;
        if(iIdx < dimN - 1)
           M.insert(iIdx + 1, iIdx) = 1.0;
    }

    // Construct matrix operation object using the wrapper class SparseGenMatProd
    Spectra::SparseGenMatProd<double> op(M);

    // Construct eigen solver object, requesting the largest dimN-2 eigenvalues
    Spectra::GenEigsSolver<Spectra::SparseGenMatProd<double> > eigs(op, dimN-2, dimN);

---> RAM for saving my sparse matrix was 25 Mb only (fine)
    // Initialize and compute
    eigs.init();

---> RAM for preparing the sparse eigenvalue calculation was 3 Gb too much (here all zeroes must have been saved also)

Can you pleas check, if you prepare really a sparse and not a dense eigenvalue calculation in the above case.

Thanks, there must be a sparse calculation Problem, the results in the end are ok, but not the space saving
(runs with O^2(n) instead of O(n) only).

Best regards, Dieter from Berlin

**Comment by yixuan** [comment]
Hi Dieter, this is because you requested too many eigenvalues (9998), and Spectra is designed to only retrieve a few eigenvalues (e.g. the largest or the smallest).
