### ISSUE TITLE
Eigen decomposition failing on a real symmetric (Laplacian) matrix 

### ISSUE THREAD

**Issue by mlivesu** [yixuan/spectra#149]
Hi, thank you for your wonderful tool. I am trying to use it to compute the smallest eigenfunctions of a triangular mesh (for functional mapping), but I am unexpectedly failing at it. The combinatorial Laplacian matrix that I am using is sparse real symmetric. 

If I try with the `SparseSymShiftSolve`
```c++
SparseSymShiftSolve<double> op(L);
SymEigsShiftSolver<SparseSymShiftSolve<double>> eigs(op,100,201,0);
eigs.init();
eigs.compute(Spectra::SortRule::LargestMagn);
```
the program crashes with the following error
`libc++abi: terminating with uncaught exception of type std::runtime_error: TridiagEigen: eigen decomposition failed`

If I try with the `SparseGenRealShiftSolve` 
```c++
SparseGenRealShiftSolve<double> op(L);
GenEigsRealShiftSolver<SparseGenRealShiftSolve<double>> eigs(op,100,201,0);
eigs.init();
eigs.compute(Spectra::SortRule::LargestMagn);
```
the solver converges but I am getting a lot of complex coefficients which are not supposed to happen since the matrix is real symmetric. If I use a geometric Laplacian (with cotangent weights), the `SparseGenRealShiftSolve` occasionally succeeds and returns only real coefficients, but this happens just on a few meshes, making me even more puzzled.

I guess I am making some silly mistake somewhere in the solver calls, but I can't really understand where...

I am attaching a small (530x530) sparse matrix for reference. For real problems matrix size can be much bigger, but already on this small ones I am failing.

[matrix.txt](https://github.com/yixuan/spectra/files/10467442/matrix.txt)

For the record, computing the eigendecomposition of the same matrix with matlab (with eigs) produces the desired result.

Thanks a lot for your help,
Marco

**Comment by yixuan** [comment]
Mathematically, the shift **CANNOT** be any one of the eigenvalues, but from what I know, the smallest eigenvalue of a Laplacian matrix is known to be zero. Try to use a negative but small value for the shift, e.g., -0.001.

**Comment by mlivesu** [comment]
Yay! This made my day
Thanks a lot :)

**Comment by yixuan** [comment]
Cool. Glad it solves the problem.
