### ISSUE TITLE
SymGEigsSolver does not produce an orthonormal system of EigenVectors

### ISSUE THREAD

**Issue by lukkio88** [yixuan/spectra#151]
Hi,

I am using spectra to solve a problem of the form

$$
\Delta \phi_i = \lambda_i M \phi_i \text{     $i=1,\ldots,n$}
$$

Specifically my $\Delta$ is a laplacian operator and $M$ is a mass matrix (both coming from mesh processing application).
Using SymGEigsSolver I get a set of eigen vectors and I pack them as columns of a matrix $\Phi$, however when I test for orthogonality, namely by doing $\Phi^T \Phi$ I don't get the identity, but something which is actually quite scaled up. Moreover they don't seem to be normalized either.

My question is whether or not there's a reccomended postprocessing or good practices in using the solver so I can extract something which is more orthogonal at least (I can always normalize them afterwards).

More specifically my test $\Phi^T \Phi$ (with 6 eigen functions) gives me something like:

```
    18286.8    -5410.53 -0.00154038    -498.062     892.863    -9664.81
   -5410.53     17856.6 -0.00059772     2074.09    -1495.89     5552.33
-0.00154038 -0.00059772     26178.5 -0.00296359  0.00163348 -0.00085545
   -498.062     2074.09 -0.00296359     13575.8     8543.06     4957.02
    892.863    -1495.89  0.00163348     8543.06     26782.2     10885.8
   -9664.81     5552.33 -0.00085545     4957.02     10885.8     21966.6
```

And as you can see diagonals entry are quite large compared to non diagonal ones.
Any suggestions? Should I just normalize each eigen vector and that's sufficient? Is there maybe a good metric to assess how *orthogonal* the extracted eigen vectors are due to numerical error?

Thank you

**Comment by yixuan** [comment]
From the output it seems that the computed eigenvalues did not converge at all. Can you provide some example data and code for debugging?

**Comment by yixuan** [comment]
By the way, for generalized eigenvalue problem $Ax=\lambda Bx$, the eigenvectors are B-orthogonal, in the sense that $x'Bx=1$ and $x'By=0$, where $x$ and $y$ are two generalized eigenvectors.

**Comment by lukkio88** [comment]
Hi, yes I realized this later. I don't remember exactly what the issue was but I think I sorted out.

**Comment by yixuan** [comment]
Great. Let me close this one first.
