### ISSUE TITLE
Spectra as a practical ARPACK replacement

### ISSUE THREAD

**Issue by szhorvat** [yixuan/spectra#154]
Spectra looks like a modern, cleaner and well maintained replacement for ARPACK. But in practice, it is quite difficult to switch out ARPACK for Spectra in existing projects. It would be nice if you could make this easier.

The main obstacles I see:

 - The Eigen dependency is problematic for projects that do not already use Eigen, or use an alternative library instead of Eigen, such as Armadillo or plain old BLAS/LAPACK. Eigen is a heavy dependency that many projects wouldn't be willing to bring in. 

    Can the Spectra interface be generalized so it could rely on other linear algebra backends and vector/matrix representations? With C++ templates, this should be feasible without performance sacrifices.

 - No C API. Typical downstream ARPACK users are projects programmed in C, or even Fortran. Providing a C API (_in addition_ to a more flexible C++ one) would go a long way of enabling such projects to swap ARPACK for Spectra. Or at least make it feasible for people to develop their own C API, for which a swappable linear algebra backend (the previous point) is a prerequisite.

Have you considered making these changes in a future major version? They could significantly expand Spectra's adoption.

**Comment by yixuan** [comment]
Hi @szhorvat, I understand that implementing the two points you mentioned would expand Spectra's use. However, one important motivation of developing Spectra is to **redesign** the API for modern applications. I think it would be controversial if Spectra starts to consider back compatibility with ARPACK.

In fact, ARPACK is still a very good and stable library. If some applications still rely on it, then just use it. Even for today, Spectra has not implemented all the functionalities of ARPACK, and in some applications ARPACK still performs better (e.g. #39), so I do not believe ARPACK will be soon replaced.

Outside Eigen, I also implemented a subset of Spectra in Armadillo via the `eigs_sym()` and `eigs_gen()` functions. But the two proposed changes may be too large for the current development of Spectra.
