### ISSUE TITLE
compilation issues with the 'Spectra::SymEigsSolver' constructor. The error message is...

### ISSUE THREAD

**Issue by dsl2501** [yixuan/spectra#157]
I'm currently using the Spectra library to solve sparse non-symmetric matrices in my C++ project. However, I'm running into compilation issues with the 'Spectra::SymEigsSolver' constructor. The error message I'm receiving is as follows:

Error C2665 'Spectra::SymEigsSolver<Spectra::SparseSymMatProd<double,1,0,int>>::SymEigsSolver': no overloaded function takes all the argument types. Project Path: C:\Users\user\Desktop\DSL2022\SparseEigen\SparseEigen.cpp
Warning C4244 'initializing': conversion from 'Spectra::SymEigsBase<OpType,Spectra::IdentityBOp>::Index' to 'int', possible loss of data. Project Path: C:\Users\user\Desktop\DSL2022\SparseEigen\SparseEigen.cpp

It seems that there is no matching constructor for Spectra::SymEigsSolver<OpType>::SymEigsSolver with OpType being Spectra::SparseSymMatProd<double, 1, 0, int>. Also, I'm getting a warning that there might be possible loss of data when initializing some variable, converting from type 'Spectra::SymEigsBase<OpType,Spectra::IdentityBOp>::Index' to 'int'. I'd appreciate if you could provide me with some insights on how to resolve this issue.

Thank you for advice in advance.

**Comment by BangShiuh** [comment]
What is your code? You should read the documentation [https://spectralib.org/doc/classspectra_1_1symeigssolver#a469d37e08be076e198c9e383236c5056] to make sure your implementation is correct. As for the warning, you might try using Use Eigen::Index instead of int.

**Comment by dsl2501** [comment]
Thank you for reply. Here follows my code. 

#include <Eigen/Core>
#include <Eigen/SparseCore>
#include <Spectra/SymEigsSolver.h>
#include <Spectra/MatOp/SparseSymMatProd.h>
#include <iostream>

int main()
{
    // Set matrix size
    const int n = 1000;
    // Construct matrix
    Eigen::SparseMatrix<double> mat(n, n);
    // Code to fill mat
    // ...

    // Construct matrix operation object using the wrapper class SparseSymMatProd
    Spectra::SparseSymMatProd<double> op(mat);

    // Construct eigen solver object, requesting the largest eigenvalue
    Spectra::SymEigsSolver< Spectra::SparseSymMatProd<double> > eigs(&op, 1, 3);

    // Initialize and compute
    eigs.init();
    int nconv = eigs.compute();

    // Retrieve results
    if (eigs.info() == Spectra::CompInfo::Successful)
    {
        Eigen::VectorXd evalues = eigs.eigenvalues();
        Eigen::MatrixXd evectors = eigs.eigenvectors();
        std::cout << "Eigenvalues:\n" << evalues << std::endl;
        std::cout << "Eigenvectors:\n" << evectors << std::endl;
    }
    else
    {
        std::cout << "Eigenvalue computation failed." << std::endl;
    }

    return 0;
}

**Comment by dsl2501** [comment]
Compilation issues contained many problems which is now solved. Among them, interestingly, UTF-8 storage of the code was one of them on Visual Studio, and we could go forward with your comment regarding Eigen::Index instead of int. Thanks a lot.
Now I have further questions which will be explained in a 'new issue' window.
