### ISSUE TITLE
SymEigsShiftSolver returns Eigenvalues but does not return Eigenvectors. 

### ISSUE THREAD

**Issue by bodhi1991** [yixuan/spectra#18]
I am leveraging the Spectra library to solve for the eigenvalues and vectors for a sparse and symmetric 60,000 X 60,000 Laplacian matrix. I have been using the SymEigsShiftSolver since that would be apt for the symmetric sparse matrix that I have. I can obtain the eigenvalues inside a minute but I do not get the eigenvectors at all. Is there an alternative that is both performance and time efficient? 

           int main()
            {
              	SparseMatrix<double> Lpl(10,10);
	        Lpl.reserve(Eigen::VectorXi::Constant(10, 3));
	       for(int i = 0; i < 10; i++)
	       {
	            Lpl.insert(i, i) = 1.0;
	            if(i > 0)
	                 Lpl.insert(i - 1, i) = 3.0;
	            if(i < 10 - 1)
	                 Lpl.insert(i + 1, i) = 2.0;
	        }

	        SparseSymShiftSolve<double> op(Lpl);
	  	SymEigsShiftSolver< double, SMALLEST_MAGN, SparseSymShiftSolve<double> >
	  		        eigs(&op, 3, 4, 0.0);
	  	eigs.init();
	  	int nconv = eigs.compute();
	  	VectorXd evalues;
	  	evalues.resize(3);
	  	if(eigs.info() == SUCCESSFUL)
	  		evalues = eigs.eigenvalues();
	  	cout << "Eigenvalues found:\n" << evalues << endl;
	  	cout <<"\nHere is the matrix whose columns are eigenvectors of the Laplacian Matrix \n"
	  		 <<"corresponding to these eigenvalues: \n"
	  		 <<eigs.eigenvectors()<<endl;
	        return 0;
            }

**Comment by yixuan** [comment]
Hi @bodhi1991 , thanks for your report.

I find that there are two issues in your example:
1. The matrix is not symmetric, so you cannot use a symmetric eigensolver.
2. You use the shift-and-invert mode with `sigma = 0`, combined with the `SMALLEST_MAGN` selection rule. This is equivalent to seeking the largest eigenvalues (in magnitude), and we have better solutions by using the `GenEigsSolver`. See the code below.

```cpp
#include <Eigen/Core>
#include <Eigen/SparseCore>
#include <GenEigsSolver.h>
#include <MatOp/SparseGenMatProd.h>
#include <iostream>

using namespace Eigen;
using namespace Spectra;
using namespace std;

int main()
{
    SparseMatrix<double> Lpl(10,10);
    Lpl.reserve(Eigen::VectorXi::Constant(10, 3));
    for(int i = 0; i < 10; i++)
    {
        Lpl.insert(i, i) = 1.0;
        if(i > 0)
            Lpl.insert(i - 1, i) = 3.0;
        if(i < 10 - 1)
            Lpl.insert(i + 1, i) = 2.0;
    }

    SparseGenMatProd<double> op(Lpl);
    GenEigsSolver< double, LARGEST_MAGN, SparseGenMatProd<double> > eigs(&op, 3, 6);
    eigs.init();
    int nconv = eigs.compute();
    VectorXcd evalues;
    evalues.resize(3);
    if(eigs.info() == SUCCESSFUL)
        evalues = eigs.eigenvalues();
    cout << "Eigenvalues found:\n" << evalues << endl;

    cout <<"\nHere is the matrix whose columns are eigenvectors of the Laplacian Matrix \n"
         <<"corresponding to these eigenvalues: \n"
         << eigs.eigenvectors() <<endl;

    return 0;
}
```

Output:
```
Eigenvalues found:
(5.70054,0)
(5.12128,0)
(4.20815,0)

Here is the matrix whose columns are eigenvectors of the Laplacian Matrix 
corresponding to these eigenvalues: 
 (-0.255558,0)   (0.424494,0)  (-0.575032,0)
 (-0.400419,0)   (0.583153,0)   (-0.61493,0)
 (-0.457023,0)   (0.518117,0)  (-0.274241,0)
 (-0.449139,0)   (0.323001,0)   (0.116685,0)
 (-0.399049,0)  (0.0983143,0)   (0.307608,0)
 (-0.325822,0) (-0.0802733,0)   (0.251161,0)
  (-0.24448,0)  (-0.175819,0)  (0.0635152,0)
 (-0.165848,0)  (-0.188018,0) (-0.0995185,0)
(-0.0968714,0)  (-0.141079,0)  (-0.148767,0)
(-0.0412172,0) (-0.0684637,0) (-0.0927431,0)
```

**Comment by yixuan** [comment]
For symmetric matrices, you may need to increase your `ncv` value. The [documentation](http://yixuan.cos.name/spectra/doc/classSpectra_1_1SymEigsShiftSolver.html) suggests a value roughly equal to two times the value of `nev`.

```cpp
#include <Eigen/Core>
#include <Eigen/SparseCore>
#include <SymEigsSolver.h>
#include <MatOp/SparseSymMatProd.h>
#include <iostream>

using namespace Eigen;
using namespace Spectra;
using namespace std;

int main()
{
    SparseMatrix<double> Lpl(10,10);
    Lpl.reserve(Eigen::VectorXi::Constant(10, 3));
    for(int i = 0; i < 10; i++)
    {
        Lpl.insert(i, i) = 1.0;
        if(i > 0)
            Lpl.insert(i - 1, i) = 2.0;
        if(i < 10 - 1)
            Lpl.insert(i + 1, i) = 2.0;
    }

    SparseSymMatProd<double> op(Lpl);
    SymEigsSolver< double, LARGEST_MAGN, SparseSymMatProd<double> > eigs(&op, 3, 6);
    eigs.init();
    int nconv = eigs.compute();
    VectorXd evalues;
    evalues.resize(3);
    if(eigs.info() == SUCCESSFUL)
        evalues = eigs.eigenvalues();
    cout << "Eigenvalues found:\n" << evalues << endl;

    cout <<"\nHere is the matrix whose columns are eigenvectors of the Laplacian Matrix \n"
         <<"corresponding to these eigenvalues: \n"
         << eigs.eigenvectors() <<endl;

    return 0;
}
```

Output:
```
Eigenvalues found:
4.83797
4.36501
3.61944

Here is the matrix whose columns are eigenvectors of the Laplacian Matrix 
corresponding to these eigenvalues: 
-0.120131   0.23053  0.322253
 -0.23053  0.387868  0.422061
-0.322253  0.422061   0.23053
-0.387868  0.322253 -0.120131
-0.422061  0.120131 -0.387868
-0.422061 -0.120131 -0.387868
-0.387868 -0.322253 -0.120131
-0.322253 -0.422061   0.23053
 -0.23053 -0.387868  0.422061
-0.120131  -0.23053  0.322253
```

**Comment by bodhi1991** [comment]
Thank you for the fast response, however I am interested in the smallest 'k' eigenvalues. I was of the impression that SMALLEST_MAGN would do the trick. Do you have any suggestion for this?

**Comment by yixuan** [comment]
`SymEigsSolver + SMALLEST_MAGN == SymEigsShiftSolver + (sigma = 0.0) + LARGEST_MAGN`.

In your original code, change `SMALLEST_MAGN` to `LARGEST_MAGN` and increase the ncv value.

**Comment by bodhi1991** [comment]
Thanks, that takes care of everything.
