### ISSUE TITLE
Sorting of eigenvalues

### ISSUE THREAD

**Issue by skn123** [yixuan/spectra#2]
I think your point is valid that all major libraries do return the eigenvalues in descending order.
However, would it be possible in the API to return the eigenvalues/vectors in a user specified order (either descending - default, or ascending) ? I think that would solve the problem. Maybe this can be a simple API addition to the file?

**Comment by yixuan** [comment]
Yes, we can do that. I'll update the code shortly.

**Comment by yixuan** [comment]
Already added. See the documentation http://yixuan.cos.name/spectra/doc/classSpectra_1_1SymEigsSolver.html.

**Comment by skn123** [comment]
I think this issue can be closed
