### ISSUE TITLE
Cannot extract all eigenpairs

### ISSUE THREAD

**Issue by jkflying** [yixuan/spectra#22]
For certain cases (on small problems) I need *all* the eigenpairs, ie. N for an NxN matrix.

Currently I get exceptions thrown if I try to set `nev` and `nec` to N, although this should be possible, even if the performance might be bad.

Here is a patch that fixes it for me. I've tested locally using my own application, but you might want to add a test for this.

I've made this an issue instead of a pull request in case I missed something and there is a reason the last eigenpair shouldn't be calculated.

```
diff --git a/src/libcore/include/libcore/spectra/SymEigsSolver.h b/src/libcore/include/libcore/spectra/SymEigsSolver.h
index a32234b..2e036b1 100644
--- a/src/libcore/include/libcore/spectra/SymEigsSolver.h
+++ b/src/libcore/include/libcore/spectra/SymEigsSolver.h
@@ -489,11 +489,11 @@ public:
         m_eps(Eigen::NumTraits<Scalar>::epsilon()),
         m_approx_0(Eigen::numext::pow(m_eps, Scalar(2.0) / 3))
     {
-        if(nev_ < 1 || nev_ > m_n - 1)
-            throw std::invalid_argument("nev must satisfy 1 <= nev <= n - 1, n is the size of matrix");
+        if(!(1 <= nev_ && nev_ <= m_n))
+            throw std::invalid_argument("nev must satisfy 1 <= nev <= n, n is the size of matrix");
 
-        if(ncv_ <= nev_ || ncv_ > m_n)
-            throw std::invalid_argument("ncv must satisfy nev < ncv <= n, n is the size of matrix");
+        if(!(nev_ <= ncv_ && ncv_ <= m_n))
+            throw std::invalid_argument("ncv must satisfy nev <= ncv <= n, n is the size of matrix");
     }
 
     ///
```

**Comment by yixuan** [comment]
Hi @jkflying, this setting is intentional, since the algorithm itself relies on it. You may find some cases where all eigenvalues can be computed, but the convergence is not guaranteed, as what you have reported in #23.
I think it should be straightforward to use an `if` condition to branch the cases and use `Eigen::SelfAdjointEigenSolver` for certain scenarios, especially when `nev` is larger than `N/2`.

**Comment by jkflying** [comment]
Thanks for the feedback. I guess this is just a limitation of the algorithm.
