### ISSUE TITLE
Diagnostics for SparseCholesky

### ISSUE THREAD

**Issue by TomJohnson-LimitState** [yixuan/spectra#24]
Hi.  We are using Spectra and Eigen here at LimitState and it has been invaluable to our application for carrying out elastic buckling analysis and modal analysis of truss structures.  To do this, we use Spectra to solve the generalized eigenvalue problem.  

The problem I'm having is that we don't know in advance if our B matrix is positive-definite (it can sometimes be semi-definite).  If B is singular, the Spectra::SparseCholesky factorization will obviously fail - I can see this in the Visual Studio debugger - Spectra::SparseCholesky::m_decomp::m_info shows as 'NumericalIssue'.  If this is the case, we simply want to inform the user. 

I can't see a way to programmatically determine whether the factorization passed or failed as the field m_decomp is private.  Our software will therefore obliviously attempt to use Spectra::SymGEigsSolver, passing in the invalid Cholesky factorization.  This results in an assertion which we can't handle very gracefully. 

The most obvious way to check if B is positive definite is (of course!) to attempt the Cholesky factorization.  Unfortunately, I can't see how to get the return status from Spectra::SparseCholesky.  I can use Eigen::LLT to do the factorization (it has a public function called info() to check for success).  But I ultimately have to throw this away as I can't feed it into Spectra::SymGEigsSolver as it doesn't have the requisite upper_triangular_solve() function).  

Would it be possible to add a public function to Spectra::SparseCholesky to detect whether a NumericalIssue has been encoutered?  

Many thanks,

Tom

**Comment by yixuan** [comment]
Hi Tom, would it be fine if I throw an exception if the factorization fails? The client code can then capture this exception when constructing the Spectra::SparseCholesky object.

**Comment by TomJohnson-LimitState** [comment]
Hi Yixuan,

Yes, that would certainly be fine for me! 

Thanks,

Tom

**Comment by yixuan** [comment]
Finally I added an `info()` function to `DenseCholesky` and `SparseCholesky` that returns the status of the decomposition. Possible values are `Spectra::SUCCESSFUL` and `Spectra::NUMERICAL_ISSUE`. This should solve your problem so I close this issue. You may reopen it if you have further troubles with it.

**Comment by TomJohnson-LimitState** [comment]
Great work.  Thanks!
