### ISSUE TITLE
fail to find eigenvalue for some cases

### ISSUE THREAD

**Issue by cfwen** [yixuan/spectra#26]
I have a matrix of size 30000x30000, very sparse, denote as A.  We know A's rank should be  29998.
I need to compute serveral singular values (ones close to 0) of A and corresponding right singular vectors. This equivalents to compute eigenvalues of AA=A'*A and corresponding right eigenvectors. My code is as following
```
Eigen::SparseMatrix<double> AA = A.transpose()*A;
Spectra::SparseSymMatProd<double> op(AA);
Spectra::SymEigsSolver< double, Spectra::SMALLEST_ALGE, Spectra::SparseSymMatProd<double>> eigs(&op, kd, max(3 * kd, 20)); // kd = 2
eigs.init();
int nconv = eigs.compute();
```
I got no eigenvalue converged and takes more then 10 seconds. 

We can use matlab to do this:
```
[V,D] = eigs(A'*A,2,'SM')
```
it takes about 0.3 second and successfully obtained 2 eigenvalues 4.2590e-18 and -5.7298e-17
Matlab makes a call to arpack internally to compute eigenvalues.

The matrix is here: https://1drv.ms/u/s!AoRwrBYa5axzleIlJ2KzlxF1Fged8w, it stores in COO format.

In another case with a matrix of 2298x2304, spectra did succeed to compute eigenvalues. So I wonder if size or matrix structures matters (two matrix have similar structure)

**Comment by cfwen** [comment]
I've tried to alter some parameters, but none works. For example, 
```int nconv = eigs.compute(1000,1e-6,3)``` 
still fails

**Comment by yixuan** [comment]
I'll take a look. Thanks.

**Comment by thongnnguyen** [comment]
I think I encounter the same problem. My matrix, however is not sparse. Here is a MWE (minimum working example) following the example on the home page

`int size = 680;
Eigen::MatrixXd M = Eigen::MatrixXd::Random(size, size);
Spectra::DenseGenMatProd<double> op(M);

int num_eigval_want = 3;
int converge_speed = 6;

Spectra::GenEigsSolver< double, Spectra::SMALLEST_REAL, Spectra::DenseGenMatProd<double> > eigs(&op, num_eigval_want, converge_speed);

eigs.init();
int nconv = eigs.compute();
t = clock() - t;

// Retrieve results
Eigen::VectorXcd evalues;//general matrix could have complex eigvals
if (eigs.info() == Spectra::SUCCESSFUL)
	evalues = eigs.eigenvalues();
else
	std::cout << "FAIL!!!!!" << std::endl;`

**Comment by yixuan** [comment]
@thongnnguyen You case can be solved by specifying a larger `ncv` parameter, e.g.,
```cpp
int converge_speed = 10;
```

**Comment by thongnnguyen** [comment]
@yixuan , thanks for your quick response.
It did converge with 
''''C++
int converge_speed = 15;
''''
in about 21 seconds (for only 3 eigenvals). Is there any other way to speed up the process?
At the end of the day, my matrix will be Hamiltonian, not just any general dense matrix. Currently, another eigensolver from my advisor (which I don't have access to the source code) solves the same size Hamiltonian in much less than that. Since we're only interested in imaginary eigenvalues (if any) of the Hamiltonian, we hope that Spectra could speed up the process as we will have to solve the Hamiltonian repeatedly many times.

**Comment by yixuan** [comment]
I had no knowledge of Hamiltonian matrices but I found this link: http://www.math.wsu.edu/faculty/watkins/slides/ham05.pdf. It seems that what you need are the eigenvalues with smallest real part **in magnitude** (absolute value), however `SMALLEST_REAL` gives you the smallest real part by its own meaning.

**Comment by cfwen** [comment]
my matrix is symmetric, eigenvalues are all real. In your doc:
```
SMALLEST_MAGN,     ///< Select eigenvalues with smallest magnitude. Applies to both symmetric and general eigen solvers.

SMALLEST_REAL,     ///< Select eigenvalues with smallest real part. Only for general eigen solvers.

SMALLEST_IMAG,     ///< Select eigenvalues with smallest imaginary part (in magnitude). Only for general eigen solvers.

SMALLEST_ALGE,     ///< Select eigenvalues with smallest algebraic value. Only for symmetric eigen solvers.
```
It seems only SMALLEST_MAGN and SMALLEST_ALGE make sense in my case. If I use SMALLEST_REAL, program crashed at line 109 in file SelectionRule.h

**Comment by yixuan** [comment]
@cfwen Sorry for the confusion. I was replying to @thongnnguyen in the previous comment. I'm still investigating your matrix.

**Comment by cfwen** [comment]
@yixuan I didn't even notice there are other comments above 🙃

**Comment by yixuan** [comment]
OK. It turns out that this code works for me:

```cpp
#include <iostream>
#include <fstream>
#include <sstream>
#include <string>
#include <Eigen/Core>
#include <Eigen/SparseCore>
#include <SymEigsShiftSolver.h>
#include <MatOp/SparseSymShiftSolve.h>

using namespace Spectra;

typedef Eigen::SparseMatrix<double> SpMat;
typedef Eigen::Triplet<double> Tri;

int main()
{
    // Construct sparse matrix
    const int size = 30000;
    SpMat A(size, size);
    // Read data
    std::vector<Tri> trilist;
    trilist.reserve(180000);
    std::ifstream file("A");
    std::string line;
    int i, j;
    double mij;
    while(std::getline(file, line))
    {
        std::stringstream ss(line);
        ss >> i >> j >> mij;
        trilist.push_back(Tri(i, j, mij));
    }
    A.setFromTriplets(trilist.begin(), trilist.end());

    SpMat AA = A.transpose() * A;

    SparseSymShiftSolve<double> op(AA);
    SymEigsShiftSolver< double, LARGEST_MAGN, SparseSymShiftSolve<double> > eigs(&op, 5, 20, -0.1);
    eigs.init();
    std::cout << "start computing..." << std::endl;
    int nconv = eigs.compute();

    std::cout << eigs.eigenvalues() << std::endl;

    return 0;
}
```

I get

```
start computing...
 4.60005e-05
 1.61084e-05
 1.60968e-05
-5.55112e-16
-1.19349e-15
```

It takes me several seconds though.

**Comment by cfwen** [comment]
thanks, I'll have a try. I also tried to use arpack (https://github.com/opencollab/arpack-ng), no problem occurred and very fast.

**Comment by yixuan** [comment]
That would be a good news. I'll compare the results and see how to improve Spectra.

**Comment by yixuan** [comment]
@cfwen This is a way too late reply, but I want to close this issue and give you some insights of what is going on.

I have rerun the experiment with the following setting:

```cpp
SymEigsShiftSolver< double, LARGEST_MAGN, SparseSymShiftSolve<double> > eigs(&op, 5, 20, -1e-6);
```

Now everything finishes within one second.

The critical thing is that we need to use a small shift value `-1e-6` instead of the previous `-0.1`. In the latter case, the eigenvalues to retrieve after shifting are too close to each other, so the convergence was pretty slow. With the new shift, only a few iterations are sufficient for convergence.
