### ISSUE TITLE
Eigenvalues are different for direct EIGEN implementation vs Spectra based EIGEN implementation.

### ISSUE THREAD

**Issue by Maharshi-kintada** [yixuan/spectra#27]
Hi,
Thanks for the fastest tool for EIGEN implementation, it's so useful for very large matrices. I am working with a FE project which is related to solving eigenvalues of a system.

I am getting different eigen values with Spectra vs direct EIGEN/MATLAB implementation. For the same matrices check.txt as A and Mcheck.txt as MM, I solved using Spectra and Eigen as follows,
The both matrices are symmetric and positive definite.

//-----------------in -----Spectra ----------
MatrixXd A(n,n);
//some file reading code here and memcpy into A and M_lin matrices here.
DenseSymMatProd<double> op(A);
SparseMatrix<double> MM(n,n);
MM.reserve(Eigen::VectorXi::Constant(n, 3));

SparseCholesky<double> Bop(MM);
int num_eigval_want = 1398;
int converge_speed = 1400;
SymGEigsSolver<double, WHICH_SM, DenseSymMatProd<double>, SparseCholesky<double>, GEIGS_CHOLESKY>geigs(&op, &Bop, num_eigval_want, converge_speed);
geigs.init();
int nconv = geigs.compute();
VectorXd evalues;
MatrixXd evecs;
if(geigs.info() == SUCCESSFUL){
evalues = geigs.eigenvalues();
evecs = geigs.eigenvectors();}
std::cout << "Generalized eigenvalues found:\n" << evalues << std::endl;
//std::cout << "Generalized eigenvectors found:\n" << evecs.topRows(num_eigval_want) << std::endl;

//-----------------in -----direct Eigen ----------
MatrixXd A(n,n);
MatrixXd MM(n,n);
//file copying code here into A and MM
GeneralizedEigenSolver<MatrixXd> ges;
ges.compute(A, MM);
cout << "The (complex) generalzied eigenvalues are (alphas./beta): " << ges.eigenvalues().transpose() << endl;

Can you please correct me, if I am doing something wrong here. The attached eig.txt (contains (freq)^2) is the values obtained by direct EIGEN/MATLAB implementation. Seig.txt (contains (freq)^2 in first column) is Spectra implementation, which is having different eigenvalues than direct EIGEN/MATLAB. 

Thanks in advance.

[check.txt](https://github.com/yixuan/spectra/files/1081267/check.txt)
[eig.txt](https://github.com/yixuan/spectra/files/1081268/eig.txt)
[Mcheck.txt](https://github.com/yixuan/spectra/files/1081270/Mcheck.txt)
[Seig.txt](https://github.com/yixuan/spectra/files/1081269/Seig.txt)

**Comment by yixuan** [comment]
Hi @Maharshi-kintada , how large is your matrix? I notice that you requested a large number (1398) of eigenvalues. If this is close to the dimension of the matrix, then probably Spectra is not the best tool to use. Spectra is intended to retrieve a small proportion of eigenvalues. (Also, did you forget to attach the result?)

**Comment by Maharshi-kintada** [comment]
Thanks for your quick reply, This is a benchmark example of known frequency for CIVIL engineering purpose which is of sizes 1400. I just requested large eigennumbers as a comparison purpose only, I did also for 15 numbers but result is same.

**Comment by yixuan** [comment]
Are the data publicly available? It would be easier to debug with a reproducible example.

**Comment by yixuan** [comment]
OK. Two quick observations:

1. `A` is not strictly symmetric. `A[0, 1] = -2e-6, A[1, 0] = 6-e6`.
2. `M` is not strictly positive definite. 60 of its eigenvalues are close to zero (absolute value <1e-12).

**Comment by Maharshi-kintada** [comment]
Yes yixuan, A check.txt is for A and Mcheck.txt is for M. The data is generated by a Finite element devoloped by our team which is part of some project. So, not publicly available. 
The A matrix is stiffness matrix while M is mass matrix, which is used for stiffness calculation in the FE code. Both are symmetric always in FE domain.
The comparison of A[0,0] wrt to A[0,1] is negligibly small. Thus can be considered symmetric.

**Comment by yixuan** [comment]
Sorry but I'm a bit confused. Doesn't "rank deficient" mean that there exist zero eigenvalues? Diagonal elements are not so relevant to the rank, determinant is.

**Comment by Maharshi-kintada** [comment]
Yes, determinant is used to decide rank deficiency. But matrix is with nonzero diagnol, it is invertible, thus non-singular or determinant is not zero.

Do you think the properties of B are the cause for the eigen value changes??? If so, how can direct EIGEN able to solve it, is my confusion.

**Comment by yixuan** [comment]
I guess we may have different definitions for certain concepts. For example the matrix
```
[1  1]
[1  1]
```
has non-zero diagonals, but it is rank-deficient and not invertible.

**Comment by Maharshi-kintada** [comment]
Yes agreed, determinant is the way of finding rank deficiency. Shall I check if the M matrix can be solved for Mx=ones column vector (n,1) ??

**Comment by yixuan** [comment]
I would point out that when B is not positive definite, there are still solvers that handle the generalized eigenvalue problems, but they have not been implemented in Spectra yet. I hope in the future I can add this feature to Spectra.

**Comment by yixuan** [comment]
By the way, since your matrices are symmetric, why not use a symmetric eigen solver? For example, in Eigen you can use `GeneralizedSelfAdjointEigenSolver `, and in Spectra there is `SymEigsSolver`. Generally symmetric solvers are much more efficient and more accurate than general solvers.

**Comment by Maharshi-kintada** [comment]
Yes, I will surely implement that symmetric matrix solver. 
I am so thankful for such a such a fast tool "Spectra".
