### ISSUE TITLE
the sign of the eigenvectors returned by SymGEigsSolver is not correct

### ISSUE THREAD

**Issue by YuchuanQiao** [yixuan/spectra#28]
Hi Yixuan,
Recently I am using spectra to solve a general sparse Ax=lamdaBx problem. I compared the results with Matlab. I found the eigenvectors had the same value but the sign is messed up. Totally half value is different. I suspect there is something wrong with the code.

The code I used is from your example code.
  typedef SparseSymMatProd<double> OpType;
  typedef SparseRegularInverse<double> BOpType;
SymGEigsSolver<double, Spectra::SMALLEST_MAGN, OpType, BOpType, GEIGS_REGULAR_INVERSE> eigs( &op, &Bop, nev, ncv );
  eigs.init( );
  int nconv = eigs.compute( n*3); // maxit = 100 to reduce running time for failed cases
  int niter = eigs.num_iterations( );
  int nops = eigs.num_operations( );
  Vector evals = eigs.eigenvalues( );
  Matrix evecs = eigs.eigenvectors( );
could you help have a check?
Thanks.
[data.zip](https://github.com/yixuan/spectra/files/1198883/data.zip)

**Comment by yixuan** [comment]
To my best knowledge the sign of the eigenvectors is undefined. If `A * x = lambda * B * x`, then `A * (-x) = lambda * B * (-x)`, which means that `-x` is also an eigenvector.

**Comment by taiyun** [comment]
@yixuan You are right.

**Comment by YuchuanQiao** [comment]
@yixuan @taiyun I knew that the different sign of eigenvectors are also eigenvectors. My question is why the result is different with Matlab, and if there is possible to generate the same sign results as Matlab?
Thanks.

**Comment by yixuan** [comment]
Unless Matlab® open sources its code. 😂

**Comment by YuchuanQiao** [comment]
Matlab use ARPACK to solve this equation. When we use Arpack directly in C++, we also get the same results as Matlab. That is why I am asking if the sign part is not implemented as ARPACK did. And eigs() function in Matlab is open source. You can see the implementation details.

**Comment by yixuan** [comment]
Technically speaking, there is no definite algorithm to determine the sign of eigenvectors. Even Matlab or ARPACK, or any other popular library, does not claim itself to be the "standard". For ARPACK, if you provide different initial vectors, you are also likely to get different signs. So if you really want to compare the results, I would suggest simply adding your own rule, e.g. always making the first non-zero element to be positive.

Spectra is not meant to be a clone of ARPACK, and again I would say that any **reasonable** use of eigenvector should not rely on its sign. Could you elaborate your demand on using the sign information?

**Comment by YuchuanQiao** [comment]
@yixuan you are right. We have some codes to tackle the sign problem. Thanks for your reminder.
By the way, Does spectra use multi-threading or do you have any plan for the multithreading version?

**Comment by yixuan** [comment]
The algorithm itself is mostly iterative, thus difficult to parallelize. However, for large matrices the bottleneck of the computation is the matrix-vector operation. Depending on the structure of your matrix, some specific parallel algorithm or library can be used to speed up.

**Comment by YuchuanQiao** [comment]
So for the algorithm itself, we could not use multi-threading for speedup? My matrix is just what I upload in this topic, however, the matrix size of most cases is around 20k*20k which is quite large and takes quite longer time. Do you have any suggestions to speedup such type problem? Thanks.

**Comment by yixuan** [comment]
Before I jump to the technical details I want to make sure a few things:

- How sparse are your A and B matrices?
- Is your B matrix positive definite?
- Have you tried the `GEIGS_CHOLESKY` method instead of `GEIGS_REGULAR_INVERSE`?

**Comment by YuchuanQiao** [comment]
Sorry for a late reply, these days I am busy with another project....

- A and B both have around 7k nonzeros for 1k*1k matrix

- B is positive definite

- I have tried GEIGS_CHOLESKY but the results almost same, no difference shown.
I checked Matlab implementation, they use
        [L,U,P,Q,D] = lu(AminusSigmaB);
        applyOP = @(v) Q * (U \ (L \ (P * (D\applyB(v)))));
for applyOP operation, lu step uses UMFpack, but I think the next step is the key feature why Matlab implementation is much much more faster. Now for this applyOP step we just use SuperLU to calculate the final result.
Are these information sufficient?
Do you have any suggestions to speedup? OpenMP, multithreading or etc?
Thanks.

**Comment by soliloquy1983** [comment]
Hi，yixuan, I have met the same problem that the sign of the eigenvector is not corret. 
However, it does not occur for all the elements of the eigenvector,  but for some columns. 
Therfore, the result is not correct, since x is not totally reversed , that is -x
My code is as follows:

**Comment by soliloquy1983** [comment]
> Thanks

Hi  yuchuan， have you resolved the problem of incorrect sign of eigenvectors?  I have met the same problems

**Comment by YuchuanQiao** [comment]
@soliloquy1983 No really solve, I just leave it to original solutions. In my situation, it is totally flipped signs. Maybe something wrong in your case?

**Comment by soliloquy1983** [comment]
> @soliloquy1983 No really solve, I just leave it to original solutions. In my situation, it is totally flipped signs. Maybe something wrong in your case?
Hi yuchuan, many thanks for your help! I will double check my data. 
My task is to resolve the basic eigenvalue equation: AX = lambdaX, where A is a real，large(1000*1000), 
asymmetrical，dense matrix.

My codes are as follows:
void GetSpectraEiegen(MatrixXd matrix, VectorXd &eigenvalue, MatrixXd &eigenvector, int k)
{
DenseGenMatProd op(matrix);
GenEigsSolver<double, LARGEST_MAGN, DenseGenMatProd>eigs(&op, k, k*2);
eigs.init();
eigs.compute();
VectorXcd evalues = eigs.eigenvalues();
VectorXd evalueR = evalues.real();
MatrixXcd evectors = eigs.eigenvectors();
MatrixXd evectorsR = evectors.real();
}
where k = 10

Do you have any suggestions of modificatons of this code, thanks a lot!

**Comment by yixuan** [comment]
I still have the opinion that there is no **correctness** of the signs of eigenvectors. Different software packages have their own ways to determine the signs, and you can talk about their **consistency** but not **correctness**. A reasonable use of eigenvectors should not depend on their signs.

**Comment by yixuan** [comment]
@YuchuanQiao Somehow I missed your question about multi-threading. Sorry about that! I feel the difference is in the LU factorization library. Matlab may have used highly optimized and possibly multi-threaded code do the factorization, and Spectra relies on Eigen to do the job. But this is already beyond the scope of Spectra, and you can easily write a wrapper class to replace Spectra's built-in class if you have access to those high-performance libraries.

The other part of this issue seems already solved, so let me close it first.
