### ISSUE TITLE
Link error with PGI compiler pgc++(version17.4) in Linux

### ISSUE THREAD

**Issue by YuchuanQiao** [yixuan/spectra#29]
Hi yixuan,
I met a compiling problem in Linux when using PGI compiler, which was fine in Windows and also fine with g++.

Eigen::internal::palign_impl<1, __m128d>::run(__m128d&, __m128d const&)':
/Eigen3.3.4/Eigen/src/Core/arch/SSE/PacketMath.h:706: undefined reference to _INTERNAL_71
::_mm_castpd_si128(__m128d)'
/Eigen3.3.4/Eigen/src/Core/arch/SSE/PacketMath.h:449: undefined reference to 

I located the problem line:
SymGEigsSolver<double, SMALLEST_MAGN, SparseSymMatProd<double>, SparseCholesky<double>, GEIGS_CHOLESKY>
    eigs( &op, &Bop, nev, ncv );
When I comment out this line, everything is ok.
I suspect there is something wrong with this line related to eigen 3.3.4.
Which version of Eigen should I use?
I also compiled with your test cases, and all cases met this compiling problem.
Do you have any idea to solve this?
thanks.

**Comment by yixuan** [comment]
It should be due to the SIMD functions that are not supported by PGI. You can try to include the
```
#define EIGEN_DONT_VECTORIZE
```
macro before including Eigen or Spectra. (http://eigen.tuxfamily.org/dox/TopicPreprocessorDirectives.html)

**Comment by YuchuanQiao** [comment]
You are so helpful.
I solve it with this include.
Thanks.
By the way, how could you find this, I also searched online, but nothing helpful info could be found.

**Comment by yixuan** [comment]
I have taken some time reading Eigen's documentation, so I have the impression of such SIMD settings. The error message of PGI is actually not so helpful if you just search it in Google.
