### ISSUE TITLE
Missing include in SparseCholesky.h

### ISSUE THREAD

**Issue by kriolog** [yixuan/spectra#31]
Compilation fails when I try using SparseCholesky module. My client code is the following:

using OpType = Spectra::SparseSymMatProd<double>;
OpType op(A);
using BOpType = Spectra::SparseCholesky<double>;
BOpType bop(B);

using SpectraEigenSolver = Spectra::SymGEigsSolver<double, Spectra::SMALLEST_MAGN, OpType, BOpType, Spectra::GEIGS_CHOLESKY>;
SpectraEigenSolver eigen_solver(&op, &bop, 3, 6);

The error is the following:
spectra/include/MatOp/SparseCholesky.h:54:18: error: ‘SUCCESSFUL’ was not declared in this scope
spectra/include/MatOp/SparseCholesky.h:55:18: error: ‘NUMERICAL_ISSUE’ was not declared in this scope

When I add ' #include "Util/CompInfo.h" ' to the SparseCholesky.h source file, the code compiles.

I use master branch and gcc compiler (gcc version 6.4.0 20170704 (Debian 6.4.0-1)).

**Comment by yixuan** [comment]
Thanks. Would you like to submit a quick PR to fix this?
