### ISSUE TITLE
input matrix from hard disk 

### ISSUE THREAD

**Issue by zhixingfeng** [yixuan/spectra#32]
Hi, 
Can spectra calculate smallest/largest eigenvalues and the corresponding eigenvectors directly on matrices stored on hard disk without loading them into memory? 

Best

Zhixing

**Comment by yixuan** [comment]
A good example of this is https://github.com/gabraham/flashpca.

**Comment by yixuan** [comment]
Since this question is not directly related to the development of Spectra, I choose to close it first. Feel free to reopen it once you have any new ideas.
