### ISSUE TITLE
can spectra be used in visual studio?

### ISSUE THREAD

**Issue by xyan123** [yixuan/spectra#33]
can the spectra library be used in microsoft visual studio?
I tried to tell vs the path of spectra but there are still some functions can't be recognized. I can't fixed it up myself, can you give some suggestions?

**Comment by yixuan** [comment]
Did you also add the Eigen library?

**Comment by xyan123** [comment]
Yes, In the Project Properties/VC ++ Directories/, I add the path of eigen and Spectra.

**Comment by xyan123** [comment]
I have fixed it! The path is ..\spectra-0.5.0\include, and I added the the wrong path ..\spectra-0.5.0 before.
Thanks!

**Comment by yixuan** [comment]
Great.
