### ISSUE TITLE
Feature request: info() for success of decomposition

### ISSUE THREAD

**Issue by sweeneychris** [yixuan/spectra#4]
Great library! I have been long searching for something that has this capability and flexibility.

It would be really great if an info() method was implemented similar to Eigen's info() for various linear solvers. This would really help to know if the user can trust the results (i.e, the arnoldi iterations converged properly, etc.) and would be consistent with the Eigen-style of things.

**Comment by yixuan** [comment]
Thanks for the suggestion!

Actually the easy way to check the status is comparing the number of converged eigenvalues (returned by `compute()`) with the requested one, but I'd like to add this `info()` function for convenience. :-)

**Comment by yixuan** [comment]
The `info()` function has been added. See http://yixuan.cos.name/spectra/doc/classSpectra_1_1SymEigsSolver.html.
