### ISSUE TITLE
Failure of test cases with spectra-0.2.0 and eigen-3.2.8

### ISSUE THREAD

**Issue by skyrulz** [yixuan/spectra#44]
Hello,
I am using spectra-0.2.0 and eigen-3.2.8 versions. I am facing issues with test cases supplied in spectra-0.2.0/test. I would like to see that all the test cases are passing successfully. As a start my interest is in successful execution of GenEigs.cpp, as i want to use GenEigsSolver. None of the test cases are passing provided along with the test suite. Attached the output of GenEigs.out file:
[GenEigs Test Failure log.txt](https://github.com/yixuan/spectra/files/1878761/GenEigs.Test.Failure.log.txt)
Looks like the Eigen values are not converging at all with this data. 

Since i am using older version (non-c++11) of C++, i updated the test/Makefile CXXFLAGS to 
-std=c++0x mentioning the c++ version explicitly. Apart from that i have not made any changes to GenEigs.cpp.

Any solution would be helpful. 

Thanks

**Comment by skyrulz** [comment]
A simple solution, apart from moving to a newer version of the spectra and eigen would be more helpful

**Comment by yixuan** [comment]
Hi @skyrulz , sorry for the delay. Both Spectra and Eigen require only C++98. C++ 11 is only used by the Catch library for the testing. If you just want to run some examples, you do not need C++ 11 at all.

**Comment by skyrulz** [comment]
Hi yixuan,

Thanks for your response. Since c++11 is needed only for catch, I don't
understand why the test cases fail for GenEigsSolver. The site values don't
converge as the output I shared. Any particular reason for the failures.

What are prerequisites for the package? I am running them on a SUSE Linux
machine.

Thanks

**Comment by yixuan** [comment]
Actually the failures in your shared log are "expected". If you take a closer look you will find that those are cases of "Smallest Magnitude" or "Smallest Imaginary Part". That is the nature of the algorithm -- it is good at computing largest eigenvalues rather than smallest eigenvalues. And that's why in newer versions of Spectra I allow these cases to fail in the test suite.

**Comment by yixuan** [comment]
If smallest eigenvalues are needed, the shift-and-invert mode should be used, see the [README section](https://github.com/yixuan/spectra#shift-and-invert-mode).

**Comment by skyrulz** [comment]
Thanks a lot for the explanation yixuan. It helped a lot.
