### ISSUE TITLE
compile  error for ./test

### ISSUE THREAD

**Issue by EDMIG** [yixuan/spectra#48]
![2018-07-04_002336](https://user-images.githubusercontent.com/30895066/42232456-09398fb2-7f21-11e8-8614-ac6f3529b47b.png)
![2018-07-04_002408](https://user-images.githubusercontent.com/30895066/42232457-09db2372-7f21-11e8-95ce-8969c472f1e6.png)

**Comment by yixuan** [comment]
Which version of Eigen are you using?

**Comment by EDMIG** [comment]
https://github.com/PX4/eigen  master branch

**Comment by EDMIG** [comment]
Something is wrong with Eigen, the stable release 3.3.4 is OK!

**Comment by yixuan** [comment]
Great.
