### ISSUE TITLE
performance compared with matlab's eigs

### ISSUE THREAD

**Issue by EDMIG** [yixuan/spectra#49]
general real eigs case:

matlab eigs:

>> A=rand(1000);
>> tic;d=eigs(A,50);toc
时间已过 2.155860 秒。
>> tic;d=eigs(A,50);toc
时间已过 2.260002 秒。
>> tic;d=eigs(A,50);toc
时间已过 1.447940 秒。
>> 

benchmark.out: 

![2018-07-05_202504](https://user-images.githubusercontent.com/30895066/42323165-bd91d82c-8091-11e8-8f6f-9f2e6126c347.png)

the time unit is second?

**Comment by yixuan** [comment]
Microseconds.
