### ISSUE TITLE
Compilation in VS2013

### ISSUE THREAD

**Issue by johnnyontheweb** [yixuan/spectra#52]
I got strange compilation errors for Spectra example code [here](https://spectralib.org/quick-start.html) in Visual Studio 2013, with Eigen 3.3.5:

Code: Select all
    Error   1   error C2039: 'Constant': is not a member of 'Eigen::SparseMatrix<double,0,int>'   eigen\src\plugins\MatrixCwiseBinaryOps.h   91   1
    Error   2   error C3861: 'Constant': identifier not found   eigen\src\plugins\MatrixCwiseBinaryOps.h   91   1

I cannot find a suitable solution in this forum or elsewhere. "Constant" is not defined in ArrayBase and neither in SparseMatrix.h. I already tried by copying the defintions of "Constant" I found in DenseBase, but nothing helps. It seems an Eigen compilation error, but I tried to get help with no success.

Can you help on this? thanks in advance

**Comment by yixuan** [comment]
Hi @johnnyontheweb ,
I have no access to VS 2013 but I compiled the code successfully with VS 2015, so I suppose this was a compiler bug. If you cannot change your compiler, I suggest you issuing a report to the Eigen community, as the message is related to an Eigen class.
