### ISSUE TITLE
Using spectra library

### ISSUE THREAD

**Issue by bpbsl1** [yixuan/spectra#54]
Can anybody help me how to use spectra library? Main page says we need to define a class that implements a certain matrix operation and create an object of one of eigen solver classes. I dont understand what it means. Any kind of help is appreciated.

**Comment by yixuan** [comment]
I suggest you starting with the examples [here](https://spectralib.org/quick-start.html).

**Comment by bpbsl1** [comment]
I looked at those examples.....I got C4996 error....I did not understand these two lines
 
   1.  DenseSymMatProd<double> op(M);
    
   2.  SymEigsSolver< double, LARGEST_ALGE, DenseSymMatProd<double> > eigs(&op, 3, 6);
What things I need to modify to make spectra work?
Thank you..

**Comment by yixuan** [comment]
It seems to be a compiling issue. I wish you could post your exact code and error message, otherwise there is little I can infer from your description.
