### ISSUE TITLE
computing time

### ISSUE THREAD

**Issue by bpbsl1** [yixuan/spectra#55]
What can be the factors that affect computing time? I have two 1000 x 1000 matrices to diagonalize and find 100 eigenvectors of both matrices.  Then, I repeat the process for 100 times. How long should it take to do this? Its taking long time for my code to do this. 

my code:

#include <Eigen/Core>
#include <Eigen/SparseCore>
#include <Spectra/SymEigsSolver.h>
#include <Spectra/MatOp/SparseSymMatProd.h>
#include <iostream>
#include<fstream>
#include<math.h>

using namespace Spectra;
using namespace std;
double fxn1(double x)
{
	if (x <= 0.5) { return -8.0*x + 4.0; }			
	if (x > 0.5) { return 0; }
}
double fxn2(double x)
{
	if (x < 0.5) { return 0; }
	if (x >= 0.5) { return 8.0*x - 4.0; }
}

int main()
{
	ofstream density1;
	ofstream density2;
	density1.open("rho1.txt");
	density2.open("rho2.txt");
	int n, N1, N2, t1;
	cout << "how many grid points you want?" << endl;
	cin >> n;
	cout << "how many particles you want for psi1?" << endl;
	cin >> N1;
	//N1 and N2 maxm. is n/2....
	cout << "how many particles you want for psi2?" << endl;
	cin >> N2;
	cout << "how many iterations you want?" << endl;
	cin >> t1;
	density1 << "#number of grid points=" << n << endl;
	density1 << "#number of particles for psi1=" << N1 << endl;
	density1 << "#number of particles for psi2=" << N2 << endl;
	density1 << "#number of iterations=" << t1 << endl;

	double xi = 0.0; double xf = 1.0; double delx = (xf - xi) / n;
	double g12 = 1000.0; double mass1 = 1.0; double mass2 = 1.0;
	Eigen::VectorXd rho1(n + 1);
	Eigen::VectorXd rho2(n+1);
	//find initial densities with fxn defined above
	for (int i = 0; i < n + 1; ++i)
	{
		rho1(i) = N1 * fxn1(delx*i);
		rho2(i) = N2 * fxn2(delx*i);
	}
	Eigen::SparseMatrix<double> M1(n + 1, n + 1);	//defining a sparse matrix
	M1.reserve(Eigen::VectorXi::Constant(n + 1, 3)); // reserving 3 nonzero elements in n+1 columns
	Eigen::SparseMatrix<double>M2(n + 1, n + 1);
	M2.reserve(Eigen::VectorXi::Constant(n + 1, 3));

	//iteration starts from here
	for (int t = 1; t < t1; ++t)
	{
		for (int i = 0; i < n + 1; ++i)
		{
			M1.insert(i, i) = 2.0 / (mass1*delx*delx) + g12 * rho2(i);
			if (i > 0) { M1.insert(i - 1, i) = -1.0 / (mass1*delx*delx); }
			if (i < n) { M1.insert(i + 1, i) = -1.0 / (mass1*delx*delx); }

			M2.insert(i, i) = 2.0 / (mass2*delx*delx) + g12 * rho1(i);
			if (i > 0) { M2.insert(i - 1, i) = -1.0 / (mass2*delx*delx); }
			if (i < n) { M2.insert(i + 1, i) = -1.0 / (mass2*delx*delx); }
		}
		// Construct matrix operation object using the wrapper class SparseGenMatProd
		Spectra::SparseSymMatProd<double> op1(M1);
		Spectra::SparseSymMatProd<double> op2(M2);

		// Construct eigen solver object, requesting the smallest ... eigenvalues
		Spectra::SymEigsSolver< double, SMALLEST_ALGE, SparseSymMatProd<double> > eigs1(&op1, N1, 2 * N1 + 1);
		//N1 is nev=no. of eigenvalues ncv>=2.nev and nev<ncv<=n
		Spectra::SymEigsSolver< double, SMALLEST_ALGE, SparseSymMatProd<double> > eigs2(&op2, N2, 2 * N2 + 1);
		//eigs is the initial residual vector

		// Initialize and compute
		eigs1.init();  //initialize residual vector eigs
		int nconv1 = eigs1.compute();

		eigs2.init();
		int nconv2 = eigs2.compute();

		// Retrieve results
		Eigen::VectorXd evalues1;
		Eigen::MatrixXd evectors1;
		if (eigs1.info() == SUCCESSFUL)
			evalues1 = eigs1.eigenvalues();
		evectors1 = eigs1.eigenvectors();

		// Retrieve results
		Eigen::VectorXd evalues2;
		Eigen::MatrixXd evectors2;
		if (eigs2.info() == SUCCESSFUL)
			evalues2 = eigs2.eigenvalues();
		evectors2 = eigs2.eigenvectors();

		density1 << "rho1:" << endl;
		density2 << "rho2:" << endl;
		for (int i = 0; i < n + 1; ++i)
		{
			double sum1 = 0.0;
			double sum2 = 0.0;
			for (int j = 0; j < N1; ++j)
			{
				sum1 += pow(evectors1(i, j), 2.0);
				sum2 += pow(evectors2(i, j), 2.0);
			}
			rho1(i) = sum1 / delx;
			rho2(i) = sum2 / delx;
			density1 << rho1(i) << endl;
			density2 << rho2(i) << endl;
		}
		density1 << endl << endl;		
		density2 << endl << endl;

		
		M1.setZero();
		M2.setZero();
	}
    return 0;
}

**Comment by yixuan** [comment]
Just got some time to look at this. In general Spectra is effective when the number of eigenvalues requested is much smaller than the dimension of the matrix, and I would say that Spectra may not be advantageous in your situation.

Some benchmarking is always helpful. I imagine a full eigen decomposition can be faster than Spectra in this case.
