### ISSUE TITLE
SelectionRule template parameter

### ISSUE THREAD

**Issue by wo80** [yixuan/spectra#61]
I was wondering why the selection rule was chosen to be a template parameter instead of a constructor argument (or function argument to `init()` or `compute()`)?

I'm trying to write a C API around Spectra and this makes it hard to create the eigensolver. The solution (or hack) used in [RSpectra](https://github.com/yixuan/RSpectra/blob/master/src/eigs_sym.cpp) (i.e. generating all code in a switch statement using macros) is rather inflexible and could be avoided if only `SelectionRule` wasn't a template parameter.

**Comment by yixuan** [comment]
Yeah, viewed from today, the original design may be questionable.

I recall that when I wrote this library, I was standing at the user's point of view. Typically when you want to compute eigenvalues, you already have a well-defined problem. You know you need the largest, or the smallest ones.

But I agree that writing a wrapper is an issue. I believe moving the selection rule to `compute()` is doable, but that will break existing code. Probably I can create a dynamic version parallel to the current one, after the whole library is stable enough.

**Comment by yixuan** [comment]
This has been [fixed](https://github.com/yixuan/spectra/commit/d6b33b8961bd90186b96c15f31625b4cb44d0ba6#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR6-R7) in the [1.y.z](https://github.com/yixuan/spectra/tree/1.y.z) branch, which is meant to be the next major version.
