### ISSUE TITLE
Where is CMakeLists.txt?

### ISSUE THREAD

**Issue by drwhitehouse** [yixuan/spectra#71]
None of your releases contain "CMakeLists.txt" how are you supposed to build them?

`CMake Error: The source directory "/data/scratch/autoinstall_spectra0.8.1_gcc8.2.0/git_repo" does not appear to contain CMakeLists.txt.`

**Comment by yixuan** [comment]
Spectra is a header-only library so you only need to tell your compiler the location of the header files. Previously I used the traditional `make` to build the tests, and @guacke has recently added `CMake` support in the `master` branch.
