### ISSUE TITLE
support for implicitly scaling/centering sparse matrix

### ISSUE THREAD

**Issue by robmaz** [yixuan/spectra#73]
irlba has center= and scale= arguments to implicitly scale and center matrices while calculating the partial svd.  This is super useful for large sparse matrices, because centering explicitly beforehand would usually turn them into dense matrices and make the svd (or even keeping them in memory) unfeasible.

Do you think this can be supported somehow? I find that Rspectra can still handle some large matrices (~1 billion entries) where irlba already croaks, which is very nice, but principal-component regression basically needs the centering step ...

**Comment by yixuan** [comment]
If I understand correctly you hope this to be implemented in the [RSpectra](https://github.com/yixuan/RSpectra) package, right?

**Comment by yixuan** [comment]
I have added this feature to the development version of RSpectra, see the example [here](https://github.com/yixuan/RSpectra/blob/master/inst/examples/svds_center_scale.R). I just need more time to document and push the new version to CRAN.

**Comment by robmaz** [comment]
Wow, that was quick. Thank you very much, I look forward to trying this out.
