### ISSUE TITLE
Memory access error during construction of SparseCholesky

### ISSUE THREAD

**Issue by okruz** [yixuan/spectra#74]
Dear yixuan,

thank you for your effort providing and maintaining the SpectrA code.

I have an issue with the SymGEigsSolver in Spectra::GEIGS_CHOLESKY mode. My problem has matrix sizes on the order of a few 100,000. If my matrix size exceeds roughly 200,000-300,000, however, I get a memory access error during the construction of the Spectra::SparseCholesky<double> object.

I tried to construct a minimal example. It isn't all that minimal but I hope you can work with it
[spectra-minimal.cpp.zip](https://github.com/yixuan/spectra/files/3703256/spectra-minimal.cpp.zip).

If I run it with 
`const size_t BASIS_SIZE_1D = 55;`
it completes after roughly 2.5 hours  and the 3D basis-size  is 55^3 = 166,375 with 51,895,117 non-zero elements for each h and o.

If, however, I set 
`const size_t BASIS_SIZE_1D = 70;`
the 3D basis-size is 343,000 and the non-zero matrix elements are 109,215,352 but the program crashes with a memory access error during the construction of the SparseCholesky object after about 2 minutes.

I think, the overlap matrix o might be weakly positive definite (in that its lowest eigenvalue might be quite small). Can that cause this behaviour?

Thanks in advance,
okruz

**Comment by okruz** [comment]
I tried to debug the problem and apparently in
`template<typename Derived>
template<bool DoLDLT>
void SimplicialCholeskyBase<Derived>::factorize_preordered(const CholMatrixType& ap)`
in SimplicialCholesky_impl.h on line 117
`StorageIndex* Li = m_matrix.innerIndexPtr();`
Li is initialized to a nullptr (when the prolem occurs) which is then dereferenced in line 184
`Li[p] = k ;                /* store L(k,k) = sqrt (d) in column k */`
leading to a memory access error.

**Comment by yixuan** [comment]
Sounds good. Hope everything works after your fix.
