### ISSUE TITLE
eigenvectors normalized?

### ISSUE THREAD

**Issue by y-yao** [yixuan/spectra#76]
Are the eigenvectors output by spectra guaranteed to be normalized?
If so, could you point me to the lines where the normalization happens, say for the real symmetric case?
I'm asking because even though small matrices always return normalized vectors for me, when I go up to (2 billion +) by (2 billion +) some of the eigenvectors seem to have normalization much less than 1.
Thank you.

**Comment by yixuan** [comment]
The output eigenvectors are the product of two orthonormal matrices. (https://github.com/yixuan/spectra/blob/master/include/Spectra/SymEigsBase.h#L430)

Each of the two matrices has been explicitly normalized. You can try to debug `matrix_V` and `ritz_vec_conv` separately and see which one causes the issue. Or it is the multiplication that makes the result problematic.

**Comment by yixuan** [comment]
Hopefully you have found the cause of the issue. Please reopen this issue if you have additional questions.
