### ISSUE TITLE
Strange checkerboard pattern

### ISSUE THREAD

**Issue by jakubcerveny** [yixuan/spectra#78]
I want to calculate the second eigenvector of the Laplacian matrix of the dual graph of a finite element mesh. The result is not completely wrong but contains a strange checkerboard pattern. Is the solution not converged or something like that?
![eigen2](https://user-images.githubusercontent.com/1349371/71285075-957e3700-2364-11ea-9e66-c2e92b1b969f.png)
When I save the matrix and solve the same thing in Octave, I get the correct result:
![eigen1](https://user-images.githubusercontent.com/1349371/71285101-a464e980-2364-11ea-9252-91e1038ee971.png)
Any pointers would be greatly appreciated. Here is an excerpt of the code:
```
   Eigen::SparseMatrix<double> L(ne, ne);
   ... // fill the matrix with insert()
   L.makeCompressed();

   SparseSymMatProd<double> op(L);
   SymEigsSolver<double, LARGEST_MAGN, SparseSymMatProd<double>>
      solver(&op, 2, 6);

   solver.init();
   int nconv = solver.compute(10000, 1e-10);

   VERIFY(solver.info() == SUCCESSFUL, "Eigensolver failed.");
   VERIFY(nconv == 2, "Could not obtain two eigenvectors");

   Eigen::MatrixXd eigenvec = solver.eigenvectors(2);

   // return result
   fvec->SetSize(ne);
   for (int i = 0; i < ne; i++) {
      (*fvec)(i) = eigenvec(i, 1);
   }
```

**Comment by yixuan** [comment]
How is the plot associated with the eigenvector? It is supposed to be a vector, right?

**Comment by jakubcerveny** [comment]
Yes, sorry for omitting that. The vector is a linearized representation of all the elements, numbered by rows. Each element has up to four neighbors, i.e., there are four edges to adjacent nodes, that is how the dual graph of the mesh is constructed. The second eigenvector is supposed to partition the graph into one positive and one negative lobe, effectively bisecting the mesh.

**Comment by yixuan** [comment]
Thanks. Is there any public matrix data that can be used for debugging (your `L` matrix)?

**Comment by jakubcerveny** [comment]
Hopefully this link contains a ZIP file with the L matrix and two vectors: https://drive.google.com/open?id=18WGE4IyhOYRpDdAGFFgXW1hyaLn2SE8t
The matrix can be loaded with `dlmread('laplace.m')` in Octave. The other two files are the second eigenvectors from Octave and from Spectra. Thank you.

**Comment by yixuan** [comment]
Hi @jakubcerveny, I've looked at the matrix and below is my conjecture.

For your matrix `L`, the largest five eigenvalues are

```
7.923141 7.809330 7.809330 7.695518 7.624510
```

This means that `L` has two identical eigenvalues, and as a result, the second and third eigenvectors are not unique. You can print the result of `solver.eigenvalues()`. If it shows 7.923141 and 7.809330, then the result should be correct.

**Comment by yixuan** [comment]
Let me close this issue first if there is no follow-up.
