### ISSUE TITLE
Running an example of documentation

### ISSUE THREAD

**Issue by kamransalehivaziri** [yixuan/spectra#82]
Dear yixuan,

Thank you so much for the beautiful library that you made. I am a theoretical physicists with a very low level programming skills. I want to use Spectra library to calculate first few (order of 10) small eigenvalues of a sparse real symmetric matrix of order (50,000 x 50,000). To start with I just download Eigen and Spectra on MacBook using Homebrew and added the flags and header paths in Xcode. I copy pasted the second example of documentation (the one for sparse matrices) and run it. It compiled and worked perfectly. Then just to see the time order of a typical run of Spectra I change the size of the matrix to n=1000. But this time the code run but with no output. In fact eigs.info() was not SUCCESSFUL.
This is the code:

`_
#include <Eigen/Core>
#include <Eigen/SparseCore>
#include <GenEigsSolver.h>
#include <MatOp/SparseGenMatProd.h>
#include <iostream>

using namespace Spectra;

int main()
{
    // A band matrix with 1 on the main diagonal, 2 on the below-main subdiagonal,
    // and 3 on the above-main subdiagonal
    int n = 1000;
    Eigen::SparseMatrix<double> M(n, n);
    M.reserve(Eigen::VectorXi::Constant(n, 3));
    for(int i = 0; i < n; i++)
    {
        M.insert(i, i) = 1.0;
        if(i > 0)
            M.insert(i - 1, i) = 3.0;
        if(i < n - 1)
            M.insert(i + 1, i) = 2.0;
    }

    // Construct matrix operation object using the wrapper class SparseGenMatProd
    SparseGenMatProd<double> op(M);

    // Construct eigen solver object, requesting the largest three eigenvalues
    GenEigsSolver< double, LARGEST_MAGN, SparseGenMatProd<double> > eigs(&op, 3, 6);

    // Initialize and compute
    eigs.init();
    int nconv = eigs.compute();

    // Retrieve results
    Eigen::VectorXcd evalues;
    if(eigs.info() == SUCCESSFUL)
        evalues = eigs.eigenvalues();
    
    std::cout << "Eigenvalues found:\n" << evalues << std::endl;

    return 0;
}
_`

And there is no output other than "Eigenvalues found: \n". I appreciate it if you answer this very basic question.

**Comment by yixuan** [comment]
Hi Kamran, this is an example of a general matrix, and in high dimensions the complex eigenvalues are not easily separated. You may want to play with a sparse symmetric matrix, whose convergence property is much better. Below is some sample code.

```cpp
#include <Eigen/Core>
#include <Eigen/SparseCore>
#include <Spectra/SymEigsSolver.h>
#include <Spectra/MatOp/SparseSymMatProd.h>
#include <iostream>

using namespace Spectra;

int main()
{
    // A symmetric band matrix with 1 on the main diagonal,
    // and some random values on the subdiagonals
    std::srand(123);
    const int n = 1000;
    Eigen::SparseMatrix<double> M(n, n);
    M.reserve(Eigen::VectorXi::Constant(n, 3));
    for(int i = 0; i < n; i++)
    {
        M.insert(i, i) = 1.0;
        if(i > 0)
        {
            const double rnd = std::rand() / double(RAND_MAX);
            M.insert(i - 1, i) = rnd;
            M.insert(i, i - 1) = rnd;
        }
    }

    // Construct matrix operation object using the wrapper class SparseSymMatProd
    SparseSymMatProd<double> op(M);

    // Construct eigen solver object, requesting the largest three eigenvalues
    SymEigsSolver< double, LARGEST_MAGN, SparseSymMatProd<double> > eigs(&op, 3, 6);

    // Initialize and compute
    eigs.init();
    int nconv = eigs.compute();

    // Retrieve results
    Eigen::VectorXd evalues;
    if(eigs.info() == SUCCESSFUL)
        evalues = eigs.eigenvalues();

    std::cout << "Eigenvalues found:\n" << evalues << std::endl;

    return 0;
}
```

**Comment by yixuan** [comment]
Let me close this first, and you can reopen if my reply does not solve your problem.

**Comment by kamransalehivaziri** [comment]
Sorry, if I didn’t reply to you. I probably were so excited about my results. Your help worked and I could do what I wanted. Thank you so my much for the amazing package and your very quick response.

All the best,
Kamran
