### ISSUE TITLE
Issues with Sparse Matrices Loaded from File

### ISSUE THREAD

**Issue by aicaffeinelife** [yixuan/spectra#83]
Hi, 
I've been trying to use the Spectra library for analyzing some sparse matrices that I have. My basic function for getting eigen pairs looks like this:
```cpp
pair<Eigen::MatrixXcd, Eigen::VectorXcd> getEigPairs(SMatrixXd &matrix, string &fname, int k){

     bool status = Eigen::loadMarket(matrix, fname);
     if (status)
     {
         printf("Matrix succesfully loaded\n");
         printf("Stats:\n");
         printf("Rows: %ld Cols: %ld, NNZ: %ld\n",  matrix.rows(), 
            matrix.cols(), matrix.nonZeros());
         // printSparseData(matrix);
     } else{
        printf("Couldn't load matrix\n");
        return {};
     } 

     Eigen::VectorXcd eigvalues; 
     Eigen::MatrixXcd eigvectors;

     Spectra::SparseGenMatProd<double> op(matrix); 
     // // last param is the convergence speed 
     cout << "Creating eig solver now...\n";
     Spectra::SymEigsSolver<double, Spectra::LARGEST_MAGN, Spectra::SparseGenMatProd<double> > eigs(&op, k, k*2);
     // Spectra::GenEigsSolver<double, Spectra::LARGEST_MAGN, Spectra::SparseGenMatProd<double> > eigs(&op, k, k*2);  

     cout << eigs.info();


     int nconv = eigs.compute(); 
     cout << nconv << std::endl;
     cout << eigs.eigenvalues() << "\n";
     if (eigs.info() == Spectra::SUCCESSFUL)
     { 
        eigvalues = eigs.eigenvalues();
        eigvectors = eigs.eigenvectors(k);
     } else{
        cout << "Error in computing eigenpairs";
     }

     return {eigvectors, eigvalues};
}

```

Here `SMatrixXd` is a typedef for a _rowmajor_ column double matrix. I have tried both `GenEigsSolver` and `SymEigsSolver`. In either of them I get an error that says:

![image](https://user-images.githubusercontent.com/21975665/75592685-ec814600-5a50-11ea-8acd-d1aa9664ad4f.png)

And for real symmetric matrices, I get the same error but with Lanczos number. Is there anything wrong I'm doing? Or is it something else?

**Comment by yixuan** [comment]
I guess you started your parameter `k` from zero, but it should be positive. Is it the case?

**Comment by aicaffeinelife** [comment]
Nope, I started with `k>=1`.

**Comment by aicaffeinelife** [comment]
Additionally, the error message is cryptic. How exactly are you computing the "subspace dimension"?

**Comment by yixuan** [comment]
Oh, it turns out that you forgot to call `eigs.init()`.

**Comment by aicaffeinelife** [comment]
I tried calling that just now. It doesn't give this error, but just segfaults. I verified that the data is actually getting loaded, and commented out other code. Any hints?

**Comment by yixuan** [comment]
One more issue found: if you have a symmetric matrix, use the `SymEigsSolver` and `SparseSymMatProd` classes, and the returned eigenvalues and eigenvectors are real-valued (`VectorXd` and `MatrixXd`). Otherwise, use `GenEigsSolver` combined with `SparseGenMatProd`, and the eigenvalues and eigenvectors are complex-valued (`VectorXcd` and `MatrixXcd`).

If segfault remains, some debugging tools such as GDB would be very useful to locate the source of error.

**Comment by aicaffeinelife** [comment]
That snippet was a small modification. I had been using the `SparseGenMatProd` and expecting a `VectorXcd` and `MatrixXcd`. My analysis narrows the segfault to when `eigs.init()` is called. I can try to go deep into the call with `gdb`.

**Comment by yixuan** [comment]
I just noticed that your sparse matrix is row-majored. That should be the source of segfault.

**Comment by aicaffeinelife** [comment]
Alright! Yeah that seemed to be the issue. I just assumed that the solver would work well with a row major matrix. It would be nice if the init threw out a simple print saying - "this is a row major matrix, exiting". Thanks for your prompt replies and help!

**Comment by yixuan** [comment]
If fact I'm surprised that this did not cause a compilation error, as col- and row-major matrices are basically two different types. :frowning:
