### ISSUE TITLE
Use of Spectra on externally-managed data?

### ISSUE THREAD

**Issue by dnbaker** [yixuan/spectra#86]
Hi,

I'm quite pleased by the support and organization of the software library, and I'd like to take advantage of it.

I'm not very familiar with using Eigen (as I often use blaze-lib), but I'd like to try to take advantage of your software. Do you know if it would there would be an easy way to specify external storage (usually row-major) and then dispatch your solver on it? (Without copying or transposing, ideally.)

Thanks!

Daniel

**Comment by yixuan** [comment]
Yes, Eigen provides the [Map](http://eigen.tuxfamily.org/dox/group__TutorialMapClass.html) class to wrap external memory into a matrix object. One complication here is that I didn't define the matrix operator for row-majored matrices, so a bit of boilerplate code is needed. If you provide some more details about your need I can show some example code here.

**Comment by dnbaker** [comment]
Thank you! That would be great.

One part of it is that I'd like to use them on blaze-lib matrices, but they're templated between row-major and column-major. There's an additional issue of padding, where blaze-lib not only aligns the memory allocated but pads each row to be a full SIMD vector, but I think I might be able to figure that on my own if I had an idea of how to wrap it.

blaze-lib matrices are templated to be <value_type, storage_order>; Since eigensolvers are much more expensive than transposition, I could transpose a blaze matrix for decomposition.

Can you provide an example of applying your data to a matrix in external memory such as this?

e.g., 

```c++
#include "blaze/Math.h"
#include <Eigen/Dense>
int main() {
    blaze::DynamicMatrix<float, blaze::columnMajor> mat(/*rows=*/100, /*columns=*/ 500);
    Eigen::Map<Eigen::Matrix<float, Eigen::dynamic, Eigen::dynamic>> map(mat.data(), 100, 500);
    // Your code here?
    // Followed by some copying to return the results, which I'm sure I could figure out
}
```

Thanks a lot for your response!

**Comment by yixuan** [comment]
In this case I think it is more straightforward to define the matrix operation directly, similar to the third example in README.

```cpp
#include <blaze/Math.h>
#include <Eigen/Core>
#include <Spectra/SymEigsSolver.h>
#include <iostream>

using namespace Spectra;
using BlazeVec = blaze::CustomVector<float, blaze::unaligned, blaze::unpadded, blaze::columnVector>;

class BlazeOp
{
private:
    const blaze::DynamicMatrix<float, blaze::columnMajor>& m_mat;
public:
    BlazeOp(const blaze::DynamicMatrix<float, blaze::columnMajor>& mat) : m_mat(mat) {}
    int rows() const { return m_mat.rows(); }
    int cols() const { return m_mat.columns(); }
    // y_out = M * x_in
    void perform_op(const float *x_in, float *y_out)
    {
        BlazeVec x(const_cast<float*>(x_in), cols());
        BlazeVec y(y_out, rows());
        y = m_mat * x;
    }
};

int main()
{
    std::srand(123);
    const int n = 100;
    blaze::DynamicMatrix<float, blaze::columnMajor> mat(/*rows=*/n, /*columns=*/n);
    // Fill a symmetric matrix
    for(int j = 0; j < n; j++)
    {
        for(int i = j; i < n; i++)
        {
            mat(i, j) = float(std::rand()) / RAND_MAX;
            mat(j, i) = mat(i, j);
        }
    }

    BlazeOp op(mat);
    SymEigsSolver<float, LARGEST_ALGE, BlazeOp> eigs(&op, 3, 6);
    eigs.init();
    eigs.compute();
    if(eigs.info() == SUCCESSFUL)
    {
        Eigen::VectorXf evalues = eigs.eigenvalues();
        std::cout << "Eigenvalues found:\n" << evalues << std::endl;
    }

    return 0;
}
```

The benefit is that you can use whatever matrix types in Blaze as long as you can compute the matrix-vector multiplication.

**Comment by yixuan** [comment]
By the way, what is the proper way in Blaze to define a `CustomVector` from const pointers? I didn't find it in the documentation so I had to use `const_cast()`.

Also remember that the example above computes eigenvalues for square symmetric matrices. If you need SVD, you need to compute `A * A' * x` or `A' * A * x`.

**Comment by dnbaker** [comment]
There seems to be an issue with CustomVector, so I usually use const_cast and then make it a `const CustomVector<type>` rather than `CustomVector<const type>`. (Good find on that, 

I see, this is very helpful.

By the way, is there any kind of packing that your project supports for symmetric matrices? I've been computing a covariance matrix in packed space, using `num_rows - row_number` entries per row to save on space, but the solver I've been using wants full rectangular form.

**Comment by yixuan** [comment]
The design of Spectra is that you don't really need the actual matrix object, but instead the matrix-vector multiplication operator. You just need to define a class for packed symmetric matrices similar to the one in the example, and then use that operator with Spectra. I know there are a number of LAPACK functions handling the packed form.

**Comment by dnbaker** [comment]
Fantastic. You're right, [ds]spmv are the functions I'd need to use for computing the matrix-vector product. (Thanks for the pointer, this will save both time and space.)
