### ISSUE TITLE
Add full LAPACK eigensolver

### ISSUE THREAD

**Issue by jalfonsi** [yixuan/spectra#90]
Hello, I'm working with sparse tridiagonal or banded matrices. In Eigen there's EigenSolver for getting all the eigenvalues/vectors of dense matrices. Is it possible to have the same implemented in Spectra (at least for matrices of size 50000)?

**Comment by JensWehner** [comment]
I am no expert, but I think the eigenvectors of a sparse matrix can very well be dense. i.e. if you need all the eigenvectors you are better off converting it to a dense matrix and using Eigen
.

**Comment by jalfonsi** [comment]
Thanks but I have already done it! Anyway, I think there should be a way to have the full eigensolver accepting small-to-medium sized sparse matrices.

**Comment by yixuan** [comment]
Hi @jalfonsi, the goal of Spectra is to compute the extreme eigenvalues of sparse matrices, based on some iterative algorithms. It is not intended to compute the full spectrum.

For your problems, eigensolver for tridiagonal matrices is available via the `Eigen::SelfAdjointEigenSolver<MatrixType>::computeFromTridiagonal()` function, and for other banded matrices, I think you just need to reduce them to tridiagonal forms and then compute eigenvalues.
