### ISSUE TITLE
Getting the eigen values/vectors following a threshold

### ISSUE THREAD

**Issue by XL64** [yixuan/spectra#91]
Hello,

I would like to get largest eigen values of a given eigen problem (eg. L-1DL-t) following a threshold.
I'm currently computing it using a overestimated number of eigen values request and truncating it but it cost much to compute more eigen values than needed.

XL.

**Comment by yixuan** [comment]
Currently this is not easy to do with Spectra. What you can try is to first compute a few eigenvalues and then test the threshold. If you need more, remove the space of computed eigenvectors from the original matrix, and then compute the next few eigenvalues.

**Comment by XL64** [comment]
Thanks for the answer.
