### ISSUE TITLE
Eigen issue with spectra

### ISSUE THREAD

**Issue by lukkio88** [yixuan/spectra#96]
Hi,

Linked to [https://github.com/yixuan/spectra/issues/95](url), which I think is sorted now.

I still cannot manage to build however, I get this error:

 ```
error: ‘Index’ in namespace ‘Eigen’ does not name a type
     typedef Eigen::Index Index;
```

Is there a specific version I need to have? I currently have installed 3.3.7.

**Comment by yixuan** [comment]
I suspect you somehow linked to an older version of Eigen. `Eigen::Index` was [introduced in Eigen 3.3](http://eigen.tuxfamily.org/index.php?title=3.3), and Spectra has been tested with Eigen 3.3.1+ without such an error message.

**Comment by lukkio88** [comment]
Hi, I've renamed the title of issue #95, since I think it's better to have everything in one place.

**Comment by yixuan** [comment]
Let me close this issue first as it is unrelated to Spectra itself. Please reopen if the problem remains.
