### ISSUE TITLE
performance problem with SymGEigsSolver

### ISSUE THREAD

**Issue by qzxuhui** [yixuan/spectra#98]
Sir:

I have a performance problem with SymGEigsSolver.
 
I have a generalized eigenvalue problem, the system is sparse, and with size `960x960`.

I want find 5 smallest eigenvalue and corresponding eigenvector.

I using spectra, I found it is hard to convergence, at I tune the parameter to let solver convergence, it takes around 14s on my computer.

I using matlab to solve the same problem, it takes 0.07s to obtain smallest 5 eigenvalue and takes 0.16s to obtain all eigen value.

## I do not know why there exist a so large gap, I already enable the `-O3` optimization. Maybe I misused the library.

My code using spectra looks like
```
#include <Eigen/Core>
#include <Eigen/SparseCore>
#include <Eigen/Eigenvalues>
#include <Spectra/SymGEigsSolver.h>
#include <Spectra/MatOp/SparseGenMatProd.h>
#include <Spectra/MatOp/SparseCholesky.h>
#include <iostream>
#include <fstream>
std::vector<Eigen::Triplet<double>> readTripletFromFile(const std::string &file_name, const int nonzero)
{
    std::vector<Eigen::Triplet<double>> coefficients(nonzero);
    std::ifstream fin;
    fin.open(file_name);
    int row, col;
    double value;
    for (int i = 0; i < nonzero; i++)
    {
        fin >> row;
        fin >> col;
        fin >> value;
        coefficients[i] = Eigen::Triplet<double>(row, col, value);
    }
    fin.close();
    return coefficients;
}

int main()
{
    const int n = 960;
    const int nonzero = 184320;
    std::vector<Eigen::Triplet<double>> coefficients_A = readTripletFromFile("data_A.txt", nonzero);
    std::vector<Eigen::Triplet<double>> coefficients_B = readTripletFromFile("data_B.txt", nonzero);
    Eigen::SparseMatrix<double> A(n, n);
    A.setFromTriplets(coefficients_A.begin(), coefficients_A.end());
    Eigen::SparseMatrix<double> B(n, n);
    B.setFromTriplets(coefficients_B.begin(), coefficients_B.end());

    Spectra::SparseSymMatProd<double> Aop(A);
    Spectra::SparseCholesky<double> Bop(B);

    const int num_solution = 5;
    const int convergence_parameter = 100;

    Spectra::SymGEigsSolver<double, Spectra::SMALLEST_ALGE,
                            Spectra::SparseSymMatProd<double>,
                            Spectra::SparseCholesky<double>,
                            Spectra::GEIGS_CHOLESKY>
        eigen_solver(&Aop, &Bop, num_solution, convergence_parameter);

    eigen_solver.init();
    int num_convergence = eigen_solver.compute();

    if (eigen_solver.info() == Spectra::SUCCESSFUL)
    {
        std::cout << "success." << std::endl;
        std::cout << eigen_solver.eigenvalues()
                  << std::endl;
    }
    else
    {
        std::cout << "failed." << std::endl;
    }
    return 0;
}
```

The full code can be found in 
https://github.com/qzxuhui/MyDiscussion/tree/master/spectra/1

Could anyone help me? Thanks for your time.

**Comment by yixuan** [comment]
Hi @qzxuhui, thanks for the report. The reason is that the solver is good at finding the largest eigenvalues, but very inefficient in finding the smallest eigenvalues (in magnitude). For regular eigenvalue problems the recommended way is to use the shift-and-invert mode via the `SymEigsShiftSolver` solver, but unfortunately I have not done that for `SymGEigsSolver`.

I will try to implement it in the next few weeks.

**Comment by qzxuhui** [comment]
Thank you, sir. Please let me know after you finished it. It will be great helpful if you attach a example of how to use your new solver.

**Comment by qzxuhui** [comment]
Sir, I want find the few smallest eigenvalues in algrbra. For example, if spectra of system is `-5,-4,-3,-2,-1,0,1,2,3,4,5`, I want find `-5,-4,-3` but not `0,-1,1`. In this case, should the shift-and-invert mode be used?

**Comment by yixuan** [comment]
I see. In that case shift-and-invert mode does not help. I noticed you used `'smallestabs'` in the Matlab code, so I thought you needed smallest magnitude.

**Comment by qzxuhui** [comment]
Sir, thank your for point out my matlab code's bug.

Sorry, I do not express my problem clear, I modify the maltab code to `smallestreal`. And I found the matlab also hard to convergence.

So I using an indirect way to obtain the smallest eigenvalue. We can  verse the roles of `A` and `B` and compute the largest eigenvalues of `inv(A)*B`. The reciprocals of these will be the eigenvalues of interest.

The idea comes from `ARPACK user guide/Templates and Driver Routines/Symmetric Drivers/Generalized Eigenvalue Problem`

## matlab
```
% I want solve A*x=lambda*B*x
phi=eigs(B,A,5,'largestreal');
lambda=1./phi;
% takes 0.043166s
```
## spectra
```
    Spectra::SparseSymMatProd<double> lhs(B);
    Spectra::SparseCholesky<double> rhs(A);
    ...
    Spectra::SymGEigsSolver<double, Spectra::LARGEST_ALGE,
                            Spectra::SparseSymMatProd<double>,
                            Spectra::SparseCholesky<double>,
                            Spectra::GEIGS_CHOLESKY>
        eigen_solver(&lhs, &rhs, num_solution, convergence_parameter);
    // takes 0.3s
```
Though there is still a gap, I do not know why there is still a gap, however, it is acceptable now.  

Thank you for your time, sir.

**Comment by yixuan** [comment]
There is a potential danger for this method. By switching the role of A and B you need to assume that A is positive definite, but it may not be the case.

**Comment by qzxuhui** [comment]
You are right, sir. Do you have any suggestion regard what we should do if directly solve smallest eigenvalue hard to convergence?

**Comment by yixuan** [comment]
1. Understand your problem. If you know A is positive definite, then smallest eigenvalues are also smallest in magnitude, and in this case the shift-and-invert mode is preferred (Matlab implicitly does this).
2. If you really need the smallest algebraic eigenvalues, then you have to use the regular mode. The convergence speed is affected by the eigen gaps (gaps between eigenvalues), and there is little we can improve.
3. Alternatively, there are other algorithms that are good at handling interior eigenvalues, for example the Jacobi-Davidson method. They may have better convergence in the case of small eigen gaps. One implementation is the [PRIMME](https://github.com/primme/primme) library, and I encourage you to try it.

**Comment by qzxuhui** [comment]
Wow, sir, thank you for your suggestions, It is great help, I can see the dawn now : )

**Comment by JensWehner** [comment]
btw. if your problem is really a 1000x1000 problem just using the Eigen Dense solvers might be actually faster than the rest.

**Comment by qzxuhui** [comment]
Sir, can we configure the solver to set tolerance? such as error is 1e-3, we can though the solver has convergenced.
