### ISSUE TITLE
Sort the returned eigenvalues according to Spectra::SELECT_EIGENVALUE

### ISSUE THREAD

**Issue by Abacn** [yixuan/spectra#99]
Hi all,

I found the results of eigenvalues so far are sorted by LARGEST_ALGE no matter which option one parse into SymEigsSolver as a template parameter. For example:

`
#include <Eigen/Core>
#include <Spectra/SymEigsSolver.h>
#include <iostream>

using namespace Spectra;

int main(int arc, char *argv[])
{
  Eigen::VectorXd X(4);
  X << 4.0 , -3.0 , 2.0 , -1.0;
  Eigen::MatrixXd M = X.asDiagonal();
  DenseSymMatProd<double> op(M);
  SymEigsSolver< double, LARGEST_MAGN, DenseSymMatProd<double> > eigs(&op, 3, 4);
  eigs.init();
  eigs.compute();
  // 4 2 -3. Should this be 4 -3 2 ? And so does the order of eigenvectors.
  std::cout << "Eigenvalues found:\n" << eigs.eigenvalues() << std::endl;
  
  return 0;
}
`

**Comment by yixuan** [comment]
Hi, there is a `sort_rule` parameter in the `compute()` function, which I think is what you need.

**Comment by Abacn** [comment]
Thanks for reminding! As sort_rule is the third parameters, this would require explicitly fill in the first two parameters. Personally I would prefer sort_rule being consistent with SelectionRule template parameter by default.

**Comment by yixuan** [comment]
I understand. The default sorting scheme is intended to be consistent with other software such as ARPACK.
